### ISSUE TITLE
Validate gef-classic changes with downstream project

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#107]
If possible it would be great if we could also build GMF and Sirius as part of of our PR verification.

Does anyone knows how this can be done with Github actions or on the command line? @azoitl IIRC you had plans to do something like this.

@Phillipus maybe you have an idea?

**Comment by Phillipus** [comment]
> @Phillipus maybe you have an idea?

Sorry, I don't know how to do this.

**Comment by azoitl** [comment]
@vogella yes I had plans to do some setup. For starting I mostly had a manual setup in mind. Mostly because I expect that the automated builds of these GMF etc. most probably pull in GEF classic via some configured p2 update site. 

Currently I run a first test with 4diac IDE. There I did it very simple I just imported the GEF Classic projects into my 4diac IDE development workspace. This is enough that 4idac IDE is using my GEF Classic development version. I know this does not scale, but it gives me some confidence.

**Comment by pcdavid** [comment]
FWIW, https://ci.eclipse.org/gmf-runtime/job/gmf-runtime-all/ builds (weekly, but this could be changed) against all target platforms supported by GMF, including `canary`, which is defined [here](https://github.com/eclipse/gmf-runtime/blob/master/releng/org.eclipse.gmf.runtime.target/canary.target) and depends on the nightlies of "everything", including GEF-Classic: `<repository id="GEF-Classic" location="https://download.eclipse.org/tools/gef/classic/latest/"/>`.

On the command-line, from GMF Runtime's root folder: `mvn -Dplatform=canary clean verify`

Sirius has an equivalent but in a separate job (https://ci.eclipse.org/sirius/job/sirius-canary) which builds daily. Its [canary](https://git.eclipse.org/c/sirius/org.eclipse.sirius.git/tree/releng/org.eclipse.sirius.targets/sirius_canary.target) target platform also consumes nightlies of everyone.

**Comment by pcdavid** [comment]
Also, note that Sirius has not (yet) moved to GitHub.

**Comment by vogella** [comment]
Thanks @pcdavid for the info.

@azoitl I think we could upload the PR build results somewhere and afterwards configure GMF to use this new location. For this the GMF build would have to introduce a parameter which we could use in such build.

The first step would be to do this manually on the command line, once we have this working we could try to automate this via Jenkins for GH action.

**Comment by azoitl** [comment]
> @azoitl I think we could upload the PR build results somewhere and afterwards configure GMF to use this new location. For this the GMF build would have to introduce a parameter which we could use in such build.

@vogella how I understood @pcdavid message and from what I see in their repo they allready have such a paramter for their maven builds.

**Comment by pcdavid** [comment]
> @vogella how I understood @pcdavid message and from what I see in their repo they allready have such a paramter for their maven builds.

There is no such parameter, as the `.target` files in GMF point to fixed locations. Yes, the `canary.target` point to a "floating" location (latest), but it's not the same as "build GMF against the result of building the specific GEF PR #XX".

Assuming your build actions publish the result of a GEF PR at a specific location, one could do some string substituion on a GMF `.target` file to point to that...

**Comment by azoitl** [comment]
> > @vogella how I understood @pcdavid message and from what I see in their repo they allready have such a paramter for their maven builds.
> 
> There is no such parameter, as the `.target` files in GMF point to fixed locations. Yes, the `canary.target` point to a "floating" location (latest), but it's not the same as "build GMF against the result of building the specific GEF PR #XX".
> 
> Assuming your build actions publish the result of a GEF PR at a specific location, one could do some string substituion on a GMF `.target` file to point to that...

As I first step I would love to just beeing able to build GMF runtime on my machine. But somehow not even that works when I use the command provided above. Should this be so?

**Comment by pcdavid** [comment]
The default target platform still points to `2021-03` which I had removed.
All the CI jobs explicitly set the target to use (and usually when I test locally I test on a specific target too) so I had not noticed.
You should be able to build GMF using `mvn clean verify -Dplatform=2021-03` (or any of the target platform from `releng/org.eclipse.gmf.runtime.target`). Normally they are all OK, see https://ci.eclipse.org/gmf-runtime/job/gmf-runtime-all.

**Comment by pcdavid** [comment]
I've pushed https://github.com/eclipse/gmf-runtime/commit/10490fe81846d4d7974d8f8e9b9bf4f413e72a31 which makes `2021-03` the new default.

**Comment by azoitl** [comment]
I'm now testing regularly against GMF Runtime, partly graphiti, 4diac IDE and WPT. I think with that we have more feedback and are saver. Therefore I'm closing this issue for now.
