### ISSUE TITLE
current update site contains old bundles

### ISSUE THREAD

**Issue by flaviodonze** [eclipse/gef-classic#113]
As state in this issue: https://github.com/eclipse-platform/eclipse.platform.releng/issues/69, the GEF update site contains outdated bundles:
![grafik](https://user-images.githubusercontent.com/24522870/190342171-5092b3dd-493e-421c-9e46-4fe46f9c2c3c.png)

According to this https://github.com/eclipse/gef-classic/pull/91 it should be `3.13.0.qualifier`.

**Comment by vogella** [comment]
Which update site? Simrel? We did not yet contribute the new release to simrel. See #114 114

**Comment by vogella** [comment]
Ah, sorry, the update side is visible.

@merks If I look at gef.aggron, we should contribute 3.14.0. Do you know why 3.12 is in the simrel?

````
  <repositories location="https://download.eclipse.org/tools/gef/classic/releases/3.14.0" description="GEF-Classic releases">
    <features name="org.eclipse.gef.sdk.feature.group">
      <categories href="simrel.aggr#//@customCategories[identifier='Modeling']"/>
    </features>
    <features name="org.eclipse.zest.sdk.feature.group">
      <categories href="simrel.aggr#//@customCategories[identifier='Modeling']"/>
    </features>
  </repositories>

````

**Comment by vogella** [comment]
@merks see https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/195829 for current to m1.

**Comment by vogella** [comment]
icu dependency should be remove in the next 2022-12 release.
