### ISSUE TITLE
Release GEF 3.15M1 and contribute to simrel

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#114]
As a "new" tradition we should release GEF Classic and contribute to the simrel. Preferrable we do this at the beginning of a release so that we can discover issues in the simrel.

Will also fix the dependency in the simrel to ICU, see https://github.com/eclipse-platform/eclipse.platform.releng/issues/69#issuecomment-1247687352

**Comment by merks** [comment]
Maybe it's a terminology thing, but do you need to "release" in order to contribute?  Normally one produces milestones at start of a cycle and produces a release near the end of the cycle...

**Comment by vogella** [comment]
@merks good idea. I started the build to produce  "3.15.0M1". Update site: https://download.eclipse.org/tools/gef/classic/releases/3.15.0M1

Any concerns to contribute this to the simrel?

cc @azoitl @pcdavid @Phillipus

**Comment by merks** [comment]
I tested contributing that repo to SimRel and it doesn't cause any validation problems so that looks good.

**Comment by vogella** [comment]
Thanks @merks I created https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/195829 

Lets wait for the others comment before adding this. Strange that simrel seems to have 3.12 and not 3.14 at the moment, see https://github.com/eclipse/gef-classic/issues/113

**Comment by merks** [comment]
For this change you should expect this version to be aggregated:

![image](https://user-images.githubusercontent.com/208716/190389110-0440d95c-bc1a-4889-b5eb-d1a8ec23d268.png)

You're probably confusing the bundle with the feature:

![image](https://user-images.githubusercontent.com/208716/190389416-fafd7bc2-6130-4132-af6d-3e197127f840.png)

**Comment by azoitl** [comment]
I would find it very good if we could manage to get GEF Classic on simrel and have regular release. But for me the whole thing is new. So please have patience. Any good place I can start to read about the process?

**Comment by vogella** [comment]
I contributed https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/195829 so that simrel GEF removes the dependency to icu.

@azoitl I created https://github.com/eclipse/gef-classic/wiki/Release-process so you could use this to familize yourself with the release process. The way I currently do it, is with "as minimal effort as possible", for the milestone release I only had to create the above Gerrit after running our release job.

**Comment by merks** [comment]
Here is documentation describing the overall process:

https://ci.eclipse.org/simrel/

That also points at the wiki:

https://wiki.eclipse.org/Simrel/Contributing_to_Simrel_Aggregation_Build

**Comment by azoitl** [comment]
Thx for the links. Have something to read for the weekend ;-)

**Comment by azoitl** [comment]
If nobody objects I would do an 3.15M3 release over the weekend. And update our simrel contribution.

@vogella last time you created to releases:
 - [3.15.0M1](https://download.eclipse.org/tools/gef/classic/releases/3.15.0M1)
 - [3.15.0m1](https://download.eclipse.org/tools/gef/classic/releases/3.15.0m1)

I would expect that one of the both is wrong may I ask witch one?

**Comment by vogella** [comment]
IIRC https://download.eclipse.org/tools/gef/classic/releases/3.15.0M1 was the correct one

**Comment by azoitl** [comment]
> IIRC https://download.eclipse.org/tools/gef/classic/releases/3.15.0M1 was the correct one

Thx. Will give it a try.
