### ISSUE TITLE
Removal of com.ibm.icu has changed behaviour of BreakIterator

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#116]
With https://github.com/eclipse/gef-classic/issues/92 we now have changed behaviour in line breaks in TextFlow Figures.

`java.text.BreakIterator` is rendering different line break behaviour in `draw2d.text.FlowUtilities` than `com.ibm.icu.text.BreakIterator`.

This means that line breaks will be different in diagram figures that use draw2d `TextFlow` components.

See https://github.com/archimatetool/archi/issues/871

Should we revert #92?

**Comment by vogella** [comment]
Can we fix the code without ICU? Platform also plans to drop it and this library has only little maintenance

**Comment by Phillipus** [comment]
> Can we fix the code without ICU? Platform also plans to drop it and this library has only little maintenance

I don't think that would be easy if it is even possible. The internal implementations of `BreakIterator` sub-classes are quite different.

**Comment by Phillipus** [comment]
Run the following code with `import com.ibm.icu.text.BreakIterator;` and again with `import java.text.BreakIterator;`:

```java
String text = "FirstPart/LastPart";

BreakIterator breakIterator = BreakIterator.getLineInstance();
breakIterator.setText(text);
int start = breakIterator.first();

for(int end = breakIterator.next(); end != BreakIterator.DONE; start = end, end = breakIterator.next()) {
    System.out.println(text.substring(start, end));
}
```

With `com.ibm.icu.text.BreakIterator` the output is:

```
FirstPart/
LastPart
```

With  `java.text.BreakIterator` the output is:
```
FirstPart/LastPart
```

**Comment by vogella** [comment]
If only draw2d.text.FlowUtilities is different, maybe we can copy the split logic into the class?

@azoitl WDYT?

**Comment by Phillipus** [comment]
The word split is one example of the difference in line break logic. There are other differences (See https://github.com/archimatetool/archi/issues/871)

**Comment by azoitl** [comment]
> If only draw2d.text.FlowUtilities is different, maybe we can copy the split logic into the class?
> 
> @azoitl WDYT?

I think it would be good if we can keep the ibm.icu out. Keeping the code in sounds reasonable. Can we just do that? But ICU BreakIterator has depends on at least three more classes.

I had also a look on java.text.BreakIterator. I noticed that there are more different breakiterators:
- Line instance
- Word instance
- Character instance

See below for what they do. Could it be that we are using wordInstance wrong? 

`Line Instance:
FirstPart/LastPart 
Some 
more 
text 
"with 
quotes" 
Test!

Word Instance:
FirstPart
/
LastPart
 
Some
 
more
 
text
 
"
with
 
quotes
"
 
Test
!

Character Instance:
F
i
r
s
t
P
a
r
t
/
L
a
s
t
P
a
r
t
 
S
o
m
e
 
m
o
r
e
 
t
e
x
t
 
"
w
i
t
h
 
q
u
o
t
e
s
"
 
T
e
s
t
!

Sentence Instance:
FirstPart/LastPart Some more text "with quotes" Test!
`

**Comment by Phillipus** [comment]
I also tested those breakiterators. Line Instance is the only one that makes sense for calculating line breaks.

If ICU is not going to be used I guess the difference in line break behaviour has to be accepted. For Archi I am going to use ICU for my GEF fork, and ship the ICU jar with it if needed.

**Comment by azoitl** [comment]
> I also tested those breakiterators. Line Instance is the only one that makes sense for calculating line breaks.

Oh. I had a look on the code and thought that it should handle also the word break quite well. But I guess I'm wrong. 

But taking a step back isn't then the line instance version broken in java.text?

**Comment by Phillipus** [comment]
I found that https://unicode-org.github.io/icu/userguide/boundaryanalysis/#line-break-boundary refers to a set of rules:

https://www.unicode.org/reports/tr14/

In that document there is reference to:

`SY  Symbols Allowing Break After    /    Prevent a break before, and allow a break after'

Clearly there is a difference between the ICU implementation and java.text.

The question is, is this acceptable for downstream users of Draw2d? For one Archi user, at least, they prefer the ICU method.

**Comment by Phillipus** [comment]
These are the ICU classes that were used in GEF/Draw2d:

```
com.ibm.icu.text.Bidi
com.ibm.icu.text.BreakIterator
com.ibm.icu.text.DecimalFormat
com.ibm.icu.text.NumberFormat
com.ibm.icu.text.MessageFormat
```

I think the critical ones are:

```
com.ibm.icu.text.Bidi
com.ibm.icu.text.BreakIterator
```

As used in:

```
org.eclipse.draw2d.text.BidiProcessor
org.eclipse.draw2d.text.FlowUtilities
```

We already see different behaviour in BreakIterator and there may be unknown differences in Bidi as well.

These are the options that I can think of:

1. Revert to using ICU
2. Carry on with java.text replacement classes but document any known differences in behavior
3. Carry on with java.text replacement classes and try to fix in Draw2d classes

I can't see (3) as being easy, as the FlowUtilities code is quite complicated and relies on the line break algorithms of BreakIterator.

(Side note - we use GraalVM as a JavaScript interpreter in Archi. GraalVM has a hard dependency on ICU4J so we are stuck with it.)

**Comment by azoitl** [comment]
I agree that 3 would be a tremendous effort. But I fear that there are anyhow some issues in the textflow helper. I noticed these when trying to fix some broken tests. Also looking at the output of the line instance above and the output in the archimate issue (archimatetool/archi/issues/871) there is definitly an issue with textflow and the quote. So some work is definitely needed.

**Comment by Phillipus** [comment]
> there is definitly an issue with textflow and the quote

I would ignore that as an edge case, as he is using two right double quotes `”`

For now I guess we decide whether to stick with `java.text` classes or revert to ICU classes.

**Comment by vogella** [comment]
I dislike that you still use your fork ;-), so let revert the affected cases to use ICU for now (if nobody objects) so that you do not need your fork and potentially remove ICU in the future.

Ok for everyone?

**Comment by Phillipus** [comment]
> I dislike that you still use your fork ;-)

I will be using it for some time, as we have made quite a few changes (that still need to be applied here). So don't revert back to ICU just for me. :-)

I think the main issue is how the change to `java.text`classes might affect downstream clients of Draw2d - text layouts might look different on existing diagrams. And we still don't know if the Bidi class has unknown changes.

ICU is still being shipped as part of the `org.eclipse.rcp` feature (see https://www.eclipse.org/eclipse/news/4.19/platform_isv.php#icu-e4-feature).

**Comment by Phillipus** [comment]
Or we could do a partial revert to ICU just for the Draw2d plug-in and only for `com.ibm.icu.text.Bidi` and
`com.ibm.icu.text.BreakIterator` I think the other changes are safe.

**Comment by azoitl** [comment]
For me reverting is perfectly fine. I also like the idea of the partial revert.

But I fear at one point we will need to do this somehow breaking change. I also looked into GEF5 but I think there everything in that respect is handled by JavaFX.

I also have to admit this is an area of programming which I'm totally new to.

**Comment by Phillipus** [comment]
> But I fear at one point we will need to do this somehow breaking change. 

Indeed, and this is why I am not sure about reverting this. If there comes a time when Eclipse platform does not include ICU then this means the dependency has to be handled here.

**Comment by vogella** [comment]
@Phillipus Can you provide a PR for the partial revert?

**Comment by Phillipus** [comment]
Close this as completed.
