### ISSUE TITLE
Please switch back to the old feature names.

### ISSUE THREAD

**Issue by wimjongman** [eclipse/gef-classic#117]
Is there a reason the features are renamed with a dash in between? It gives us a lot of trouble.

e.g.

BIRT wants to jump to the latest GEF classic, but it can't because it consumes other consumers of GEF that use the old feature naming. Since gef and draw2d are singletons, there is no way out.

As a result, I have to chase all my upstream providers that use gef and draw2d or stick myself on a lower version. It is a catch-22.

Please switch back to the old feature naming.

**Comment by vogella** [comment]
Only products depend on features AFAIK. How can a rename affect plugins?

**Comment by wimjongman** [comment]
Updates sites, features, target definitions, and products depend on features. 

I did not say it affected plugins.

**Comment by wimjongman** [comment]
I see it was already reverted, but for some reason, we have the wrong feature IDs in the update site.

https://github.com/eclipse/gef-classic/commit/b6dbc05df36460d1d90a6c18f0a93340639b917e

**Comment by vogella** [comment]
Ok, great to hear

**Comment by wimjongman** [comment]
Sorry, I mean GEF has the wrong feature id's in the update site.

**Comment by wimjongman** [comment]
The change was made here https://github.com/eclipse/gef-classic/commit/b6dbc05df36460d1d90a6c18f0a93340639b917e but it looks like it was never released. Can GEF make a new release?

**Comment by azoitl** [comment]
GEF classic plans to have a new release with the next simrel release. The M1 release can be found here: https://download.eclipse.org/tools/gef/classic/releases/3.15.0M1/
Does this help?

**Comment by wimjongman** [comment]
It does!! Thanks @azoitl

**Comment by vogella** [comment]
The latest update site of the release should also contain the old IDs. Iirc @merks did this revert before the release

**Comment by wimjongman** [comment]
It does. For some reason, I landed on 1.13.

Sorry for the noise.
