### ISSUE TITLE
Replace deprecated methods isEnqueued()

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#122]
There are two instances of `isEnqueued()`. This method has been deprecated since Java 16:

https://github.com/eclipse/gef-classic/blob/9e560cf2b2d63e03d6721a9346895d4ce44471f2/org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalViewerKeyHandler.java#L218

https://github.com/eclipse/gef-classic/blob/9e560cf2b2d63e03d6721a9346895d4ce44471f2/org.eclipse.gef/src/org/eclipse/gef/tools/SelectionTool.java#L141

The JavaDoc says:

> Deprecated. This method was originally specified to test if a reference object hasbeen cleared and enqueued but was never implemented to do this test.This method could be misused due to the inherent race condition or without an associated ReferenceQueue. An application relying on this method to release critical resources could cause serious performance issue. An application should use `ReferenceQueue` to reliably determine what reference objects that have been enqueued or `refersTo(null)` to determine if this reference object has been cleared.

It seems to me the easiest thing would be to replace with `refersTo(null)` like this:

`cachedNode.refersTo(null)` and `cachedHandlePart.refersTo(null)`

JavaDoc:

> Tests if the referent of this reference object is obj. Using a null obj returns true if the reference object has been cleared.

WDYT?

**Comment by Phillipus** [comment]
> It seems to me the easiest thing would be to replace with `refersTo(null)` like this:

Scrap that idea because I just realised that `refersTo(null)` was introduced in Java 16 so this won't compile on earlier versions.

**Comment by vogella** [comment]
Should we move GEF to Java 17? Simrel already uses this one.

**Comment by Phillipus** [comment]
> Should we move GEF to Java 17? Simrel already uses this one.

Are there downstream clients still on 11?

**Comment by azoitl** [comment]
Yes. Especially when you are using Xtext or Xtend your are currently stuck with Java 11 max. This will change with the next release of Xtext. But not sure yet how stable it will be.

**Comment by Phillipus** [comment]
I'm not even sure this line does anything useful anyway:

```
if (cachedNode.isEnqueued())
            return null;
```

The line following is this:

```
return (GraphicalEditPart) cachedNode.get();
```

JavaDoc says about `get()`

> Returns this reference object's referent. If this reference object has been cleared, either by the program or by the garbage collector, then this method returns null.

So it will return null anyway.

**Comment by azoitl** [comment]
I think you are right. When we are already at cleaning up this code we could also typefy this two weakreferences to reduce the number of warnings. Do you want to do that @Phillipus?

**Comment by Phillipus** [comment]
Thanks for the feedback and merge. :-)

**Comment by azoitl** [comment]
Thx for the patch and finding this problem.
