### ISSUE TITLE
Maintain Canvas Position under Mouse during Zooming

### ISSUE THREAD

**Issue by azoitl** [eclipse/gef-classic#124]
Currently the ZoomManager tries to maintain the center of the canvas while zooming. This can lead to strange zooming behavior and users loosing track where they are. This happens especially in larger diagrams. 

In 4diac IDE we implemented a different behavior where the point under the mouse is preserved. So if your mouse is over an element and you zoom in or out this element is not moving.

We find that a very convenient behavior and therefore I'm consider to upstream it. However before doing so I would like to ask if this behavior is a better general behavior. 

@Phillipus, @pcdavid what do you think about it?

**Comment by Phillipus** [comment]
Could it be optional behaviour?

**Comment by azoitl** [comment]
Good point. As it is currently rather deeply woven into the zoom logic I haven't thought about it But yes it could be nicely separated and made configurable. For that I would propose an IZoomScrollPolicy interface which the ZoomManager would use to calculate the new scrollposition and apply it. The current implementation could be a default policy and be used unless something else is set. And I could then provide my new one rather easily.

**Comment by azoitl** [comment]
@Phillipus with your inspiration I created a first PR #125 to show a potential solution. What to you think? Is this in the direction you imagined. I applied the new ZoomScroolPolicy to the logic editor for testing. What should be marked is while it is working it is not behaving as naturally as in 4diac IDE. The reason is there we have a border around the drawing canvas. This has to reasons: 1. it gives the user visual feedback where the diagram ends
2. for zooming and scrolling there is enough spare space that the content under the mouse always stays.

I'm considering to upstream that as well if people are interested.

**Comment by Phillipus** [comment]
@azoitl Yes, that looks great! I think your idea of using a policy pattern fits in with the existing GEF design patterns.

**Comment by azoitl** [comment]
> @azoitl Yes, that looks great! I think your idea of using a policy pattern fits in with the existing GEF design patterns.

Thx. It is also much nicer then what we currently have in 4diac IDE. However after sleeping it over I think we should really first decide on #100. Because I guess this feature is something that we shouldn't have duplicated in GEF and ZEST.
