### ISSUE TITLE
Palette not colored correctly in dark theme

### ISSUE THREAD

**Issue by kjsmita6** [eclipse/gef-classic#128]
cc @vogella 

Eclipse GEF	GEF Classic Draw2d	3.14.0.202206170857	org.eclipse.draw2d
Eclipse GEF	GEF Classic GEF (MVC)	3.14.0.202206170857	org.eclipse.gef

Coming here from https://github.com/eclipse-platform/eclipse.platform.ui/issues/259. Our Eclipse RCP product uses a GEF-based editor and palette. The palette is not colored correctly when the platform is in dark theme:
![image](https://user-images.githubusercontent.com/9405706/200885821-39d3177d-7e96-4b01-b4fd-ab507134524e.png)
(notice the rest of the workbench is dark correctly)

The main editor canvas is dark correctly, it is just the palette view which does not get colored.

However, on rare occasions, I have gotten it to work. It seems that (sometimes) putting the OS in dark mode and also having Eclipse in dark mode can help, although doing this as I'm writing this issue isn't working.

**Comment by Phillipus** [comment]
> when the platform is in dark theme

Is this on Windows or Mac?

**Comment by Phillipus** [comment]
I have a custom version of GEF and Draw2d. This version can set the colors of the palette using a theme ColorDefinition set in a customised copy of Eclipse's dark theme. When I have more time I'll try to contribute this to GEF code here.

**Comment by kjsmita6** [comment]
> Is this on Windows or Mac? Do you mean OS dark theme or Eclipse / RCP dark theme?

This is Mac, and I meant Eclipse dark theme.

> I have a custom version of GEF and Draw2d. This version can set the colors of the palette using a theme ColorDefinition set in a customised copy of Eclipse's dark theme. When I have more time I'll try to contribute this to GEF code here.

We have our own dark theme color overrides as well, including for the GEF editor. Does this not work for the palette then without your changes?
 
> I found, though, that a very dark palette background does not work for some toolbar icons. So it may be that you need another icon set for the palette in dark theme.

I have found the opposite for the times it has worked. On those rare occasions when the palette shows in dark mode, the icons and text are correctly matching the background.

**Comment by Phillipus** [comment]
> I have found the opposite for the times it has worked. On those rare occasions when the palette shows in dark mode, the icons and text are correctly matching the background.

We have some black icons like arrows and so doesn't work for us. Something to bear in mind if the palette is changed when in dark mode.

**Comment by azoitl** [comment]
@Phillipus I would see how we can fix that for the palette. But I have a hard time how to generally and backwards compatible fix it for anything that is using the colors in ColorConstants. From my experiments and investigations it strongly depends when you first access ColorConstants if you get the right ones or not. 

But while I'm writing here, is it possible that the ColorConstants initialization is not targeting the SystemColors from the display but accessing the theming engine?

**Comment by Phillipus** [comment]
This is what I did:

https://github.com/archimatetool/archi/commit/b79e907903345e4701fee389ccef95239dea81b0

https://github.com/archimatetool/archi/commit/a3523ca9cfd1652f5c09d9a24195e0844c03c1e9

https://github.com/archimatetool/archi/commit/8f24e1a087cb12f8f592cf63dc8219de192e1e0a

> is it possible that the ColorConstants initialization is not targeting the SystemColors from the display but accessing the theming engine?

I need to dig deeper into this to remind myself of the issues around this.

**Comment by azoitl** [comment]
> > is it possible that the ColorConstants initialization is not targeting the SystemColors from the display but accessing the theming engine?
> 
> I need to dig deeper into this to remind myself of the issues around this.

After a quick look maybe the code you have in getThemeColor could be used.

**Comment by Phillipus** [comment]
This subject needs more research.

I guess what I'm trying to say is that if Eclipse theme settings are supported in the palette and in the `Graph` and `FigureCanvas` components we should be careful about setting backgrounds to black automatically, it should at least be configurable.

With Archi, diagrams contain black connections that aren't visible if the background canvas is black. These connection colors are not part of a theme, they are black because the user made them black. A diagram's colors should not be part of the host application's color scheme in the same way that I would not want my Photoshop image to be changed when I turn dark theme on.

**Comment by Phillipus** [comment]
Here's what Archi looks like with custom dark theme.

<img width="1552" alt="Archi dark theme" src="https://user-images.githubusercontent.com/600504/201039519-d64af14e-b640-4b75-9cad-a3857f5c7c30.png">

**Comment by azoitl** [comment]
Hmh this is a hard one. I guess it depends a lot on the application that is done with GEF. However I would not compare most of them (also Archi) not with Photoshop. Out of curiosity I experimented with DrawIO. My tool to explore creative usability features. In their dark mode the adjust also the colors of the drawing. But I agree with you that this will be very hard for us to do in GEF Classic in a generic way.

**Comment by kjsmita6** [comment]
Some more (not super helpful) info. We have another GEF editor that has its own palette separate from the one in the OP. This one looks correct in dark mode:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/9405706/201250827-f3a13fc3-d0bc-452a-8a07-f503dded600b.png">

I didn't make either of these and I couldn't tell the difference from the code. If there's any info I can provide to help let me know.

**Comment by Phillipus** [comment]
On Mac if Eclipse theming is disabled and the following entry in the app's `Info.plist` file is not present or is false the palette will be dark:

```
    <key>NSRequiresAquaSystemAppearance</key>
    <true/>
```

The palette in the above screenshot looks heavily customised. If you look at the GEF code you'll see that colors are taken from `ColorConstants` which take its colors from the `SWT` class color constants.

**Comment by vogella** [comment]
Any plans to include this in the standard GEF? Would be great to have a themeable GEF?

**Comment by Phillipus** [comment]
> Any plans to include this in the standard GEF? Would be great to have a themeable GEF?

I have some code for theming in my GEF fork. I guess the next stage is I could submit a draft PR to further this.

**Comment by azoitl** [comment]
@vogella As I was contemplating on that topic over the weekend. Should GEF have its own theme entries or should GEF use the existing ones? If the later where can I find a list of theme colors. Because with that I could setup the GEF Classic color with the given theme colors which would then hopefully better blend into the workbench.

**Comment by mikevwdriver** [comment]
When we addressed palette theming in our product, we had to replace 3 classes used by GEF that have hardcoded colors.

PaletteColorUtil
ColorConstants
ColorConstants#SystemColorFactory

**Comment by vogella** [comment]
@mikevwdriver can you create PR for the removal of the hard-coded colours?

**Comment by vogella** [comment]
> @vogella As I was contemplating on that topic over the weekend. Should GEF have its own theme entries or should GEF use the existing ones? If the later where can I find a list of theme colors. Because with that I could setup the GEF Classic color with the given theme colors which would then hopefully better blend into the workbench.

Without having looked at the code, if GEF would use SWT constants (and if they would be correctly initialized) OR if GEF would use the Colors and Fonts extension point we could add CSS instructions to style them for the dark theme. Colors and Fonts are preferences and preferences can be configured with CSS settings.

**Comment by azoitl** [comment]
> > @vogella As I was contemplating on that topic over the weekend. Should GEF have its own theme entries or should GEF use the existing ones? If the later where can I find a list of theme colors. Because with that I could setup the GEF Classic color with the given theme colors which would then hopefully better blend into the workbench.
> 
> Without having looked at the code, if GEF would use SWT constants (and if they would be correctly initialized) OR if GEF would use the Colors and Fonts extension point we could add CSS instructions to style them for the dark theme. Colors and Fonts are preferences and preferences can be configured with CSS settings.

GEF is using the SWT constants but in the form `SystemColorFactory.getColor(SWT.COLOR_WIDGET_BACKGROUND);`. These acquired colors are stored as static final fields. As the themeing is changing the SWT colors later as we access them we have the problem here. What would be a quick fix is to ask the theming engine for the colors. I  have done something similar in 4diac IDE. However what I'm to dumb to find is how I find the according theme strings for  the SWT.COLOR_* constants.

**Comment by kjsmita6** [comment]
@azoitl "theme strings"? Do you mean just the color IDs like you would override in an extension (like `org.eclipse.jdt.ui.Javadoc.foregroundColor`)?

We have a similar thing for getting theme colors. We check the theme registry for the current theme first and see if the color is there. Otherwise we get it from the theme manager.

**Comment by mikevwdriver** [comment]
> @mikevwdriver can you create PR for the removal of the hard-coded colours?
The solution we used was not a general solution, so it would not be a good fit.

**Comment by azoitl** [comment]
> @azoitl "theme strings"? Do you mean just the color IDs like you would override in an extension (like `org.eclipse.jdt.ui.Javadoc.foregroundColor`)?
> 
@kjsmita6 the color IDs so that I can look in the theme registry.

> We have a similar thing for getting theme colors. We check the theme registry for the current theme first and see if the color is there. Otherwise we get it from the theme manager.

Yes exactly this is what I had in mind to do.

**Comment by Destrolaric** [comment]
Hi everyone. @dbeaver team is currently working on resolving this issue. We plan to allow configuring colors via the `org.eclipse.ui.themes` endpoint.

**Comment by azoitl** [comment]
> Hi everyone. @dbeaver team is currently working on resolving this issue. We plan to allow configuring colors via the `org.eclipse.ui.themes` endpoint.

@Destrolaric this is great!

**Comment by vogella** [comment]
> > Hi everyone. @dbeaver team is currently working on resolving this issue. We plan to allow configuring colors via the `org.eclipse.ui.themes` endpoint.
> 
> @Destrolaric this is great!

Indeed. A talk from the @dbeaver was the starting reason why we revived GEF classic

**Comment by franz-ms-muc** [comment]
+1 from me.

**Comment by kjsmita6** [comment]
Github didn't give me a notification when it was created, but #140 is to fix this.

**Comment by azoitl** [comment]
Thx to @Destrolaric for your hard work. As we merged your patchset today I'll close this issue. It will be part of the 3.16 release (#134 )
