### ISSUE TITLE
Fix / update eclipse.org/GEF

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#138]
eclipse.org/GEF does not point to "our" repo and talks about latest release for Oxygen. We should delete all unnecessary contant and just point to Github.

@azoitl do you know where to update this site?

**Comment by azoitl** [comment]
@vogella I'm not sure which page you are talking about. Can you provide the full link? Do you mean: https://www.eclipse.org/gef/?

This is currently hosted at a git repo. I would know where to update. Any suggestions how to change?

**Comment by vogella** [comment]
Yes https://www.eclipse.org/gef/ is the one. 

I would just remove any content and point to our repo and the JavaFX repo. If you have PR / Gerrit I can give feedback.

**Comment by azoitl** [comment]
I can try to propose something. However we have to be a bit carefull as this page is the common page for GEF 5 and GEF classic. So I would also ask for Matthia's approval.

I would suggest to remove the Release 5.0.100 Available section and update the Current status section such that there GEF is part of the simrel and available in two flavors: GEF 5 and GEF Classic and let both link to their respective github pages. 

There is still some nice content hidden in the git repo of this page. I was thinking of introducing a subpage (e.g., https://www.eclipse.org/gef/gef-classic) where this content could be resurrected. And we could use this sub-page to advertise GEF Classic. Or should we keep everything on github?

**Comment by azoitl** [comment]
For documentation purposes here is the gerrit patch: https://git.eclipse.org/r/c/www.eclipse.org/gef/+/197680

Will try to review the infromation available in the web-page repo and consider where to best put it on our git-hub page (e.g., contributing, readme or wiki).

**Comment by vogella** [comment]
I think this one is done. Thanks @azoitl

**Comment by azoitl** [comment]
Yes think so too.
