### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gef-classic#141]
Hi,

I'm investigating a behavior change between GEF 3.14 and 3.15 which breaks one of our tests in Sirius. Not necessarily a bug/regression in GEF, it might be something on our side.

Anyway, it seems GEF 3.14 and 3.15 have not been tagged in git, so it's not obvious which range of commits I should look at for possible changes. I can guess based on dates, but it would be nice if the exact commits used for the official releases were tagged in git.

**Comment by azoitl** [comment]
I totally forgot about this. I created the release tags and also updated the checklist in #134.
