### ISSUE TITLE
Test errrors on Jenkins

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#142]
GEF verification build constantly reports the following teste errors:

[org.eclipse.draw2d.test.TextFlowWrapTest.testNestedInlineFlows](https://ci.eclipse.org/gef/job/gef-classic-master/3470/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testNestedInlineFlows/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testHardWrapping](https://ci.eclipse.org/gef/job/gef-classic-master/3470/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testHardWrapping/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testInlineFlow](https://ci.eclipse.org/gef/job/gef-classic-master/3470/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testInlineFlow/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testTruncatedWrapping](https://ci.eclipse.org/gef/job/gef-classic-master/3470/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testTruncatedWrapping/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testSoftWrapping](https://ci.eclipse.org/gef/job/gef-classic-master/3470/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testSoftWrapping/)

See https://ci.eclipse.org/gef/job/gef-classic-master/

Anyone knows how to fix these?

**Comment by Phillipus** [comment]
I've been looking at this. These fail locally at all points in the recent commit history. The last success was on 29 October - https://ci.eclipse.org/gef/job/gef-classic-master/3393/ Did anything change in terms of target, Jenkins setup, or suchlike? One thing I noted was changing the font name in BaseTestCase affects the test runs:

https://github.com/eclipse/gef-classic/blob/dd09de502b0fb300f3d7bbe34e53700dcebf9366/org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/BaseTestCase.java#L27

**Comment by Phillipus** [comment]
These tests pass on Windows. It may be due to a different font used on a Linux runner.

**Comment by Phillipus** [comment]
All tests pass on Windows if `com.ibm.icu.text.*` classes are replaced with `java.text.*` classes as we did in https://github.com/eclipse/gef-classic/commit/6b6eba6093e4f62536bec7d2f198aa961765cfa9

What I don't understand is how these tests passed before now.

**Comment by Phillipus** [comment]
I could get these test to pass on Linux Mint if I installed the Tahoma font and reverted https://github.com/eclipse/gef-classic/commit/9e560cf2b2d63e03d6721a9346895d4ce44471f2
