### ISSUE TITLE
Icon updates

### ISSUE THREAD

**Issue by kjsmita6** [eclipse/gef-classic#144]
https://github.com/eclipse/gef-classic/tree/master/org.eclipse.gef/src/org/eclipse/gef/internal/icons

Most of the icons in here haven't been updated in 20 years. When they appear on the Canvas/anywhere it is honestly a bit jarring.
![Screenshot 2023-01-20 at 11 02 10 AM](https://user-images.githubusercontent.com/9405706/213746170-a44dc761-382f-4ceb-9296-1c8985ec017d.png)

The cursor doesn't match the system cursor (on Mac it's black but this is white), it is slightly bigger than my cursor (and not even the same shape), and it is much more blurry. This photo doesn't do justice how bad it looks in reality.

Is there a possibility of updating these? Ideally it is just a decoration on the system cursor. Remaking these images in higher resolution would be nice too since many people have 2k/4k monitors nowadays.

**Comment by vogella** [comment]
@Destrolaric could you provide an update with fresher icons from you product?

**Comment by Destrolaric** [comment]
@vogella I think yes. It should be ready within the week.

**Comment by kysmith-csg** [comment]
Any way to make this un-stale? It's been over a week ;)

**Comment by azoitl** [comment]
I planned to work on this in the next two weeks or so. Will unstale it then.

**Comment by azoitl** [comment]
Oh I mixed that up. I wanted to work on the cursors.
