### ISSUE TITLE
Unit Tests are failing

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#150]
I just noticed that even though the build action completes successfully, there are many failing tests. For example, here's a recent build:

https://github.com/eclipse/gef-classic/actions/runs/4518703236/jobs/7958746089

The raw log on that shows several failures.

**Comment by azoitl** [comment]
Interesting. I see here two issues.

1.  Failing tests should be reported. Maybe @vogella when he set-up the build infra disabled the reporting as we have some tests that are constantly failng
2. The current log shows that the tests are not executed as eclipse plugin tests. AFAIK this is the reason for the `java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.draw2d.ColorConstants` errors. Because when I run the tests locally on my machine these are not showing.

But I'm not sure what we should do with that.

**Comment by Phillipus** [comment]
> Because when I run the tests locally on my machine these are not showing.

Are you running the tests locally using Maven or in Eclipse's JUnit runner? If the latter, the `Display` class might get initialised correctly but not when running from Maven.

**Comment by azoitl** [comment]
Locally in Eclipse. Not yet in Maven. I thought there is something for also running with maven correctly. But I'm very bad in that thing.

**Comment by Phillipus** [comment]
> Locally in Eclipse.

I came across this problem before with Archi. Tests would run fine in Eclipse but not in Maven. I found that Eclipse was initialising`Display#getCurrent` but Maven wasn't.

If we look at this commit we can see that `ColorConstants` used to initialise the Display:

https://github.com/eclipse/gef-classic/commit/93042dca3e62ed4f0ff0aedbd58e58327d98fc12

```java
class SystemColorFactory {
		private static Color getColor(final int which) {
			Display display = Display.getCurrent();
			if (display != null)
				return display.getSystemColor(which);
			display = Display.getDefault();
			final Color result[] = new Color[1];
			display.syncExec(new Runnable() {
				public void run() {
					synchronized (result) {
						result[0] = Display.getCurrent().getSystemColor(which);
					}
				}
			});
			synchronized (result) {
				return result[0];
			}
		}
	}
```

But that initialisation has been removed. Perhaps this is the case here?

**Comment by azoitl** [comment]
This code has been re-added as it was API. However Draw2D shouldn't use it anymore. Hmh. Have to dig deeper.

**Comment by Phillipus** [comment]
> This code has been re-added as it was API. 

Ah, OK, I see that in a later build. Perhaps then it is not called?

**Comment by azoitl** [comment]
With the latest patches from @Destrolaric the colors in ColorConstants are provided by `PlatformUI.getWorkbench().getThemeManager()` can it be that during maven tests we don't have that? 

For 4diac IDE we have special a special test setup which runs the tests in an eclipse environment. AFAIK this has something to do with the surefire thingy. But I was not involved in the setup.

**Comment by Phillipus** [comment]
> With the latest patches from @Destrolaric the colors in ColorConstants are provided by `PlatformUI.getWorkbench().getThemeManager()` can it be that during maven tests we don't have that?

Yes, it might be that the Workbench is not initialised and needs to be. One of the first failures in the log is:

```
java.lang.ExceptionInInitializerError
  at org.eclipse.zest.tests.GraphTests.setUp(GraphTests.java:42)
  Caused by: java.lang.IllegalStateException: Workbench has not been created yet.
  at org.eclipse.zest.tests.GraphTests.setUp(GraphTests.java:42)
```

And this might lead to the other failures.

**Comment by azoitl** [comment]
I compared our setup with GEF classic ones. And tried something new: PR #151. I hope this helps.

**Comment by Phillipus** [comment]
@azoitl I found this:

https://www.eclipse.org/forums/index.php/t/1104081/

Perhaps we need to use those surefire settings?

**Comment by azoitl** [comment]
> @azoitl I found this:
> 
> https://www.eclipse.org/forums/index.php/t/1104081/
> 
> Perhaps we need to use those surefire settings?

currently both are set to false I can give it a try with my PR #152 151

**Comment by Phillipus** [comment]
I think the key setting is `<product>org.eclipse.platform.ide</product>` if we want to use the workbench in tests.

**Comment by azoitl** [comment]
Updated my PR #151 with both lets see.

**Comment by azoitl** [comment]
It looks like the changes I did fixed it for the Draw2d tests. Wil add them to the zest tests as well as they are also failing with the color problem.

**Comment by Phillipus** [comment]
Side issue - why is the Automatic Rebase Action running every time a comment is made in an issue?

https://github.com/eclipse/gef-classic/actions/workflows/rebase.yml

**Comment by Phillipus** [comment]
> @vogella set that up. I have unfortunately no idea how this works.

It's OK, I understand it now. It's triggered on a new comment but doesn't actually do anything unless needed.

**Comment by Phillipus** [comment]
@azoitl Some GitHub actions are failing to run properly and are queued for hours. I just cancelled one of yours and re-started it - https://github.com/eclipse/gef-classic/actions/runs/4532517465

**Comment by azoitl** [comment]
> @azoitl Some GitHub actions are failing to run properly and are queued for hours. I just cancelled one of yours and re-started it - https://github.com/eclipse/gef-classic/actions/runs/4532517465

@Phillipus I noticed that as well and also tried it. Seemed that it didn't work for me. However given your comment with the eclipse dependency introduced to draw2d I don't think my PR should be merged. I think we should wait for a potential fix from @Destrolaric and then deactivate the unstable/failing textflow tests and then fail builds where tests are failing. Otherwise problems like these will slip through. What do you think?

**Comment by Phillipus** [comment]
@ Agree. It would be better to refactor the Color changes to the GEF plug-in which already has a dependency on `org.eclipse.ui.workbench` and keep draw2d dependent only on SWT so it can be used stand-alone. I'm not sure whether one of the GET unit tests will trigger a dependency on the the workbench, so we'll wait and see.

There are other failing tests. See https://github.com/eclipse/gef-classic/issues/142

**Comment by azoitl** [comment]
@Phillipus I was referring to these failing tests. As these are strongly defendant on the font I would deactivate this test (i.e., TextFlowWrapTest).

**Comment by Phillipus** [comment]
@azoitl Sorry, yes, I misread that part of your sentence. :-)

**Comment by azoitl** [comment]
Also I wrote my message in a haste between two meetings. Shouldn't do that.
