### ISSUE TITLE
Add baseline check to Tycho build

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#16]
Maven Tycho supports since a while to run a API baseline check. We should enable this so that we do not break GEF consumers unintentional.

**Comment by azoitl** [comment]
I would like to take over this task. However I must confess I would first need to read a bit on that. Do you have a pointer for me where to start?

**Comment by azoitl** [comment]
Nevermind, after some more googeling and reading I think I know what needs to be done. Working on a first pull request.

**Comment by vogella** [comment]
Can you send a PR? Would be nice to have this in ASAP

**Comment by vogella** [comment]
Done via https://github.com/eclipse/gef-classic/pull/23/commits/8769f0a648e47a6be5bd0a15b672eb912ccf4a48 Thanks @azoitl

**Comment by azoitl** [comment]
I have the patch ready [1]. But messed up my GIT.  Therefore I would need the pull request for issue #8 merged first if that is not to big of a problem.


[1] https://github.com/azoitl/gef-classic/tree/BaselineCheck

**Comment by azoitl** [comment]
Ok now I'm confused. How did you get my patch? Still struggling with this strange github workflow.

**Comment by vogella** [comment]
You seem to have added it to https://github.com/eclipse/gef-classic/pull/23
