### ISSUE TITLE
Foreground Color Not Updated When Text Displayed is One Character

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#173]
I'm reporting this bug from Bugzilla here because I can reproduce it on Mac and it also affects Archi and might affect 4Diac and other GEF-based tools:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=581803

The Snippet is at https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=289027

It's Mac only. 

In Archi I created some figures with text of only one character "A" and each figure's text foreground color is displayed incorrectly.

@azoitl Can you or a colleague check this on a Mac?

**Comment by Phillipus** [comment]
This is an issue with SWT in the `GC` class on Mac at line 1793:

```java
public void drawText (String string, int x, int y, int flags) {
	if (handle == null) SWT.error(SWT.ERROR_GRAPHIC_DISPOSED);
	if (string == null) SWT.error(SWT.ERROR_NULL_ARGUMENT);
	NSAutoreleasePool pool = checkGC(CLIPPING | TRANSFORM | FONT | FOREGROUND_FILL);
	try {
		int length = string.length();
		if (length == 0) return;
		boolean mode = true;
		switch (data.textAntialias) {
			case SWT.DEFAULT:
				/* Printer is off by default */
				if (!handle.isDrawingToScreen()) mode = false;
				break;
			case SWT.OFF: mode = false; break;
			case SWT.ON: mode = true; break;
		}
		handle.saveGraphicsState();
		handle.setShouldAntialias(mode);
		if (length == 1 && (flags & SWT.DRAW_TRANSPARENT) != 0) {
			doFastDrawText(string, x, y);
		} else {
			doDrawText(string, x, y, flags);
		}
		handle.restoreGraphicsState();
	} finally {
		uncheckGC(pool);
	}
}
```

It's the lines:

```java
if (length == 1 && (flags & SWT.DRAW_TRANSPARENT) != 0) {
    doFastDrawText(string, x, y);
} 
```

If I bypass that length check the foreground color is displayed correctly.

This optimisation was introduced here - https://github.com/eclipse-platform/eclipse.platform.swt/commit/2a2325b0699615424fc557f8d6db2190dd304048

**Comment by Phillipus** [comment]
In order to report this as a SWT bug I need a pure SWT snippet. So far I can't reproduce this in pure SWT. Can anyone help?

**Comment by azoitl** [comment]
> In order to report this as a SWT bug I need a pure SWT snippet. So far I can't reproduce this in pure SWT. Can anyone help?

I have no Mac for testing. But have you tried modifying one of the existing SWT snippet (e.g., the [label](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet108.java) or [canvas](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet245.java) snippet)

Ah I see I was maybe to slow. Sorry busy day.

**Comment by Phillipus** [comment]
I took a closer look at the caching optimisations for text in the `GC` class - https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/cocoa/org/eclipse/swt/graphics/GC.java

It makes assumptions that are wrong for a `GC` that is re-used to draw many different instances of text strings as Draw2d does. I don't know if someone at SWT will remove that optimisation, but here's a monkey patch to work around the problem in Draw2d's `SWTGraphics` class should anyone need it:

```java
// Monkey patch to workaround https://github.com/eclipse-platform/eclipse.platform.swt/issues/631 on Mac
// If on Mac and string length == 1
if("cocoa".equals(SWT.getPlatform()) && s != null && s.length() == 1) { //$NON-NLS-1$
    try {
        // Get protected field GCTextData.Cache from GC
        Field fieldTextDataCache = gc.getClass().getDeclaredField("textDataCache"); //$NON-NLS-1$
        fieldTextDataCache.setAccessible(true);
        
        // Get instance of GCTextData.Cache
        Object cache = fieldTextDataCache.get(gc);
        
        // Get method "release" and invoke it, clearing the cache
        Method release = cache.getClass().getMethod("release", new Class[] {}); //$NON-NLS-1$
        release.setAccessible(true);
        release.invoke(cache, new Object[] {});
    }
    catch(Exception ex) {
        ex.printStackTrace();
    }
}
```

**Comment by Phillipus** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/632 has now been committed and so this won't be an issue in Eclipse 4.28. So closing this one.
