### ISSUE TITLE
Nightly builds not uploaded to p2 repository

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#175]
The artifacts uploaded to the  [p2 repository](https://download.eclipse.org/tools/gef/classic/latest/) date back to the 3rd of April, meaning they're almost 2 weeks old. 

Shouldn't the build job automatically upload the artifact from the latest (successful) build?

**Comment by azoitl** [comment]
I checked in the 4diac IDE jenkins setup there we have an `export GDK_BACKEND=x11` as pre maven execution step. ll try to get that in.

**Comment by ptziegler** [comment]
> I checked in the 4diac IDE jenkins setup there we have an export GDK_BACKEND=x11 as pre maven execution step. ll try to get that in.

I was about to mention that. The "No more handles" error seems to indicate that there is no X11 server. running I.e. the tests are executed in headless mode and fail because there's no graphic support.

**Comment by ptziegler** [comment]
Hm... for [our](https://ci.eclipse.org/windowbuilder/job/org.eclipse.windowbuilder/1217/consoleText) builds, we explicitly start an Xvnc session before executing the Maven run. Which is the same approach that is used for the GitHub runs.

I sadly don't have access to our Jenkins script, but I would assume there's something along the line of:

```
stage('Build') {
	steps {
		wrap([$class: 'Xvnc', takeScreenshot: false, useXauthority: true]) {
			sh 'mvn clean verify'
		}
	}
}
```

Where Xnvc is provided by [this](https://plugins.jenkins.io/xvnc/) plugin.

**Comment by azoitl** [comment]
Let me give it a try.

**Comment by azoitl** [comment]
We have a nightly build. Thx @ptziegler for noting and helping! PR #177 was the solution.

**Comment by azoitl** [comment]
In order to notice this earlier I added email sending for failed jenkins builds (PR #178). If anyone wants to get them es just add your email and file a PR.
