### ISSUE TITLE
Replace all GEF Legacy mentions with GEF Classic

### ISSUE THREAD

**Issue by azoitl** [eclipse/gef-classic#20]
In many names and text through the GEF classic repo the old name GEF Legacy is used. For consistency and clean-up this should be updated.

**Comment by vogella** [comment]
I see this text also in feature.xml. Can you also update the feature text?

**Comment by azoitl** [comment]
Sure in the next days I wanted to work through each project step by step and update any description if possible. Can you please assign this issue to me.

**Comment by azoitl** [comment]
Would you like again to have the changes per project? For most projects it would be just a single line.

Should the update site:
`http://download.eclipse.org/tools/gef/updates/legacy/releases/`
 also be changed as part of that issue. If yes I would change legacy to classic, or?

**Comment by vogella** [comment]
> Would you like again to have the changes per project? For most projects it would be just a single line.

Feel free to combine.
> http://download.eclipse.org/tools/gef/updates/legacy/releases/

We should also create new update sites but I assume this will be done via #9 The old update sites should remain as they are to avoid breakage in GEF users.

**Comment by vogella** [comment]
Looks like you fixed that @azoitl if you find more, just send an PR, no need for a new issue.
