### ISSUE TITLE
Palette tooltip is out of screen

### ISSUE THREAD

**Issue by nvannr** [eclipse/gef-classic#204]
I'm opening this issue about palette tools tooltips going out of the window and consequently out of screen sometimes causing it to be cut off, it was raised here before:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=442856

example here: https://bugs.eclipse.org/bugs/attachment.cgi?id=246526

I believe it could be fixed by moving the tooltip depending on the window dimensions and original display point here:
https://github.com/eclipse/gef-classic/blob/7d2343b3b8112f3fd129c0e9b488b9a7105d34f2/org.eclipse.draw2d/src/org/eclipse/draw2d/ToolTipHelper.java#L96

**Comment by azoitl** [comment]
I'll tried to reproduce this issue with the latest GEF Classic (3.16.0RC1) and with the palette of the logic editor example I could not reproduce this problem under Linux. 

Can you please provide more feedback when this is happening for you? 
How could I reproduce and debug it?

**Comment by nvannr** [comment]
I have the issue on GEF 3.13.0 on windows.

I did test it on linux after seeing your comment but there indeed isn't the same problem, the tooltip is displaced to not go out of screen.

**Comment by Phillipus** [comment]
I can't reproduce this.

@nvannr Can you please provide details of your Windows version, screen resolution and what screen scaling you use?

**Comment by nvannr** [comment]
I'm using windows 11, 1920x1080 res and 100% scale (multiple screens), I do notice that it comes an goes if I change the scaling and or position of the screen where the application is, as if it's sometimes not registered properly that there is no adjacent screen for the popover to overflow in. 

I can reproduce it easily doing this with a 3 screen configuration: The main screen is in the middle with the application displayed fullscreen on it, Then I switch the position of the main screen so that it is on the right and display a tooltip that could have overflown on the right when the screen was in the middle. The tooltip still tries to overflow to the right even though there is no display there anymore.

**Comment by ptziegler** [comment]
FYI: This issue is likely solved via https://github.com/eclipse-gef/gef-classic/pull/726, which should ensure that the tooltip is always contained by the current monitor.
