### ISSUE TITLE
[GTK] Cursor created with GIF format images renders incorrectly

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gef-classic#208]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=575448 reported a while ago on SWT by @Phillipus.

For example on the GMF Runtime'e GeoShape example, when using the "Rectangle Types" tool:

https://github.com/eclipse/gef-classic/assets/10608/85d21531-d118-4d5a-bfde-636c890cb416

A Sirius user reported this [recently](https://www.eclipse.org/forums/index.php?t=msg&th=1113080&goto=1859256&#msg_1859256) which finally triggered me to investigate.
I confirm that the workaround mentiond by @Phillipus in the bugzilla (using PNG versions of the cursor and mask) fixes the problem for me.

I replaced [`Tree_Add.gif`](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.gef/src/org/eclipse/gef/internal/icons/Tree_Add.gif) and [`Tree_Add_Mask.gif`](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.gef/src/org/eclipse/gef/internal/icons/Tree_Add_Mask.gif) with the PNG versions from the archive on the bugzilla, and this fixes the issue for me (for this particular cursor) on the example above.

Note that there is something fishy in how [`SharedCursors`](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.gef/src/org/eclipse/gef/SharedCursors.java) creates its cursors: it calls `createCursor("icons/Tree_Add_Mask.gif", "icons/Tree_Add.gif")`, but `createCursor(String sourceName, String maskName)` expects the source first and the mask second.

**Comment by azoitl** [comment]
When I, some years ago, tried to fix this problem with better images and masks I could fix it for Linux but it broke on Windows. I thought I'm not smart enough for that at left it as is.  However I find the solution with the png cursors quite intriguing. Especially as the latest [Eclipse User Interface Guidelines](https://eclipse-platform.github.io/ui-best-practices/#ui-graphics) discourage the use of gifs. 

@Phillipus would it be much work to port your changes back to GEF classic?

**Comment by Phillipus** [comment]
> @Phillipus would it be much work to port your changes back to GEF classic?

Not so easy. I didn't actually change anything in the GEF code. I made my own PNGs and cursors, like this:

https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor/src/com/archimatetool/editor/diagram/tools/ExtCombinedTemplateCreationEntry.java

**Comment by azoitl** [comment]
Ah I see. But would you be willing to contribute the pngs. Especially as you already have them in low and high res.

**Comment by azoitl** [comment]
Ah I'm dumb I missed the thumbs up @Phillipus. Therefore I tried today to use the existing images and turn them into pngs. But my results where not as nice as yours. So thanks @Phillipus I'll use them and provide an appropriate PR in the next days.
