### ISSUE TITLE
Issue with zoom levels and drawing after update

### ISSUE THREAD

**Issue by kjsmita6** [eclipse/gef-classic#216]
Hello, after updating to the latest Eclipse and GEF 3.16, our GEF editor doesn't zoom properly anymore. If the zoom level is NOT 100%, things are not drawn where they should be, and no zooming happens.

For example, observe the blue grouping that is selected, but the resizing controls (which is where the selection bounds are, and where I can actually interact with the item) are below and slightly to the right.
![image](https://github.com/eclipse/gef-classic/assets/9405706/d67578e1-0d0a-4975-81ae-0b1f0a7d935e)

(at 89% zoom).

---

Observe the Outline view on the right. The blue outline shown is where the viewport should be, but you see the actual editor is slightly above again (you can see the same blue grouping from above should be at the very bottom but it isn't).
![image (1)](https://github.com/eclipse/gef-classic/assets/9405706/1a53a9a9-c1cd-4da7-b2ad-51a780a0b9b3)

---
At 100% zoom things are where they should be,
![image](https://github.com/eclipse/gef-classic/assets/9405706/6746ae21-e3e0-4c28-a62c-badb60f44f82)

But at different zoom levels they are drawn in the incorrect location (also the size is the same).
![image](https://github.com/eclipse/gef-classic/assets/9405706/c5bc067d-1d64-4a93-a7df-c1f5cc3746df)

I have the Map item selected but I clicked in the middle of the editor to do it, even though it's drawn in the top left. At lower zooms it moves to the bottom right.
![image](https://github.com/eclipse/gef-classic/assets/9405706/85c23071-d3b4-47de-8329-b9440fe600c5)

Again, here I clicked in the middle to select it (after spending a while to find it) even though it is somewhere else.

---

Here you can see strange behavior when zooming, the selection area is zoomed correctly and moves but the actual items are drawn as if they are 100% zoom (in the incorrect location).

https://github.com/eclipse/gef-classic/assets/9405706/7bbb1975-b408-49c1-870d-10845ac47d22

(as you can see it is very hard to find things).

---

Was something changed regarding this in the release? This release shouldn't have been breaking. Please advise as we would really like to use the latest Eclipse/GEF but this is a big issue.

Eclipse GEF	GEF Classic GEF (MVC)	3.14.0.202306071707	org.eclipse.gef
Eclipse GEF	GEF Classic Draw2d	3.13.0.202306071707	org.eclipse.draw2d

**Comment by Destrolaric** [comment]
Similar in nature issue in DBeaver, only labels are scaled
https://github.com/eclipse/gef-classic/assets/20579256/01d7e8ab-1649-4913-abf6-875d1baf979e

**Comment by Destrolaric** [comment]
https://github.com/eclipse/gef-classic/pull/197/files Possible cause

**Comment by vogella** [comment]
cc @ptziegler

**Comment by ptziegler** [comment]
Is there a simple example to reproduce this problem? This way I could just revert this change locally and see whether this repairs the zoom.

**Comment by azoitl** [comment]
@kjsmita6 @Destrolaric what was the GEF version you used before the ugrade 3.14 or 3.15. In 3.15 there was a change with the ZoomMangers. Are you provding your own ZoomManager or use the default one?

**Comment by ptziegler** [comment]
@azoitl Thanks. I've created the example file and was able to reproduce it as well.

This problem seems to have been introduced with 4cbd9b2fca2d15df4710b6058a1df6af79a6100d

**Comment by ptziegler** [comment]
The code when scale != 1.0 has been changed in ScalableLayeredPane. I assume that's why everything is still working with 100% zoom.
```
if (scale == 1.0) {
	super.paintClientArea(graphics);
} else {
	ScaledGraphics g = new ScaledGraphics(graphics);
	boolean optimizeClip = getBorder() == null || getBorder().isOpaque();
	if (!optimizeClip)
		g.clipRect(getBounds().getCropped(getInsets()));
	g.scale(scale);
	g.pushState();
	paintChildren(g);
	g.dispose();

	Graphics graphicsToUse = getScaledGraphics(graphics);
	if (!optimizeClip) {
		graphicsToUse.clipRect(getBounds().getShrinked(getInsets()));
	}
	graphicsToUse.scale(scale);
	graphicsToUse.pushState();
	paintChildren(graphics);
	graphicsToUse.popState();

	if (graphicsToUse != graphics) {
		graphicsToUse.dispose();
	}
	graphics.restoreState();
}
```

**Comment by azoitl** [comment]
> The code when scale != 1.0 has been changed in ScalableLayeredPane. I assume that's why everything is still working with 100% zoom.
> 
> ```
> if (scale == 1.0) {
> 	super.paintClientArea(graphics);
> } else {
> 	boolean optimizeClip = getBorder() == null || getBorder().isOpaque();
> 
> 	Graphics graphicsToUse = getScaledGraphics(graphics);
> 	if (!optimizeClip) {
> 		graphicsToUse.clipRect(getBounds().getShrinked(getInsets()));
> 	}
> 	graphicsToUse.scale(scale);
> 	graphicsToUse.pushState();
> 	paintChildren(graphics);
> 	graphicsToUse.popState();
> 
> 	if (graphicsToUse != graphics) {
> 		graphicsToUse.dispose();
> 	}
> 	graphics.restoreState();
> }
> ```

Damn, I really tested that patch. Okay I will investigate further. Thx @ptziegler for finding it.

**Comment by azoitl** [comment]
with fixes for this issue and for #215 how would we do a 3.16.1 release. I guess first creating a 3.16.x branch and cherry pick both solutions or?

**Comment by kjsmita6** [comment]
That would work, yeah. Could be time to create a policy for this, maybe always leave behind a branch for patches like this. So when 3.17 is released, create a 3.17 branch for patches (in case there need any) and move master to 3.18-snapshot. any small fixes can go to 3.17 branch and also on master, but big things can be left off 3.17.

**Comment by azoitl** [comment]
In the mean-time I created an R_3_16_maintenance branch (https://github.com/eclipse/gef-classic/tree/R3_16_maintenance) and cherry picked the two fixes to it. I also updated the release plan todo list (#210).

The open point is now how to do a 3.16.1 release. Here help would be greatly appreciated.

**Comment by kysmith-csg** [comment]
I see one here (weird url so I didn't find it at first) - https://download.eclipse.org/tools/gef/classic/releases/

**Comment by azoitl** [comment]
The relase urls should be documented in several places. I thought I had them at least in the readme and on the webpage. If not I may need to update it.
Thre release pages are filled by jenkins jobs. I'm not really good in these. Also I guess some versions in the affected plugins would need to be bumped, or?

**Comment by azoitl** [comment]
What I forgot we also have a nightly build release side: https://download.eclipse.org/tools/gef/classic/latest/
This can be handy for you to test our fixes.

**Comment by ptziegler** [comment]
> Also I guess some versions in the affected plugins would need to be bumped, or?

If I understand the [numbering](https://wiki.eclipse.org/Version_Numbering) correctly, `org.eclipse.gef` needs to be bumped to 3.14.1 and the `org.eclipse.draw2d` to 3.13.1 (on the 3.16 branch). I think those are the only two that have been modified.

**Comment by azoitl** [comment]
> > Also I guess some versions in the affected plugins would need to be bumped, or?
> 
> If I understand the [numbering](https://wiki.eclipse.org/Version_Numbering) correctly, `org.eclipse.gef` needs to be bumped to 3.14.1 and `org.eclipse.draw2d` to 3.13.1 (on the 3.16 branch). I think those are the only two that have been modified.

How about features? Also these?

**Comment by ptziegler** [comment]
> How about features? Also these?

I think so:

> Otherwise, increment the feature's service number if any contained plug-in or feature increases their service number.

Which means both the draw2d and gef feature should be 3.16.1

**Comment by azoitl** [comment]
I created PR #221 for that. I hope I got everything.
