### ISSUE TITLE
[Zest] "Reveal All" button should not be in Graph class

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#226]
I've just tested the recent changes to the Zest code with the addition the "Reveal All" button hard coded into the `Graph` component.

https://github.com/eclipse/gef-classic/blob/21a67b28c34dc6308c1272b798b15ccd8fde6fb5/org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java#L187-L198

I don't think that this button should be present in the `Graph` component, `Graph` should be a "pure" extension of `FigureCanvas` with no additional UI buttons, menu items or dialogs.

Hard coding these UI elements into the `Graph` component is not good practice in terms of accessibility, internationalization and user experience.

See also - https://github.com/eclipse/gef-classic/pull/207#issuecomment-1618577563

My suggestion is to separate the reveal/hide node functionality out (and the default should be off) and let clients decide if and when to use it in their own UI components.

**Comment by azoitl** [comment]
This has been done in PR #235.
