### ISSUE TITLE
Change About text

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#25]
Currently the about say: 
Gef legacy code

I do not see an option to change this in the UI, but we can ask the foundation to do so. Should we also call it gef-classics or a better description? WDYT? @azoitl

**Comment by azoitl** [comment]
For consistency I would say yes. I now tried to follow _GEF Classic_ in  any human readable text and gef-classic when refering to the repo. Would you agree on that wording?

**Comment by vogella** [comment]
Sounds good to me. Can you open a help ticket to change the about text?

**Comment by azoitl** [comment]
Sure: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1122

**Comment by vogella** [comment]
Looks like the help issue was done. Thanks Alois
