### ISSUE TITLE
Clarify the status and roadmap/planned changes

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gef-classic#27]
Hi,

First, thanks for your efforts in reviving GEF Legacy/Classic.

As maintainer of GMF Runtime and Sirius, the previous status of GEF Legacy being in 'pure maintenance' mode, while it meant there were no new features or bug fixes, had also the side benefit that GEF was very stable (in the sense of "not a moving target").
I see that you are starting to make changes like https://github.com/eclipse/gef-classic/issues/8 which, while good by themselves, mean downstream projects will now need to follow GEF Classic development closely and possibly adapt to those changes (and plan for it).

In particular, GMF Runtime currently targets Java 8, and when the version of GEF Classic with the change above hits the SimRel I will need to make a GMF Runtime release which targets Java 11. Is this planned for 2022-06? 2022-09? https://github.com/eclipse/gef-classic/issues/21 might also impact downstream projects (GMF Runtime, Papyrus, Sirius, Capella...) if you start *removing* deprecated APIs.

Is there a roadmap somewhere where we can see the kinds of changes you plan, and get an idea of when they will appear in the SimRel? Maybe just a GitHub milestone grouping issues planned for a particular SimRel?

Don't get me wrong, it's cool that GEF is alive again, but a *lot* of projects depend on GEF working "as it has always worked", so please be careful when considering changes and avoid changes "for the sake of changes".

As a side note, the project description at https://projects.eclipse.org/projects/tools.gef still indicates GEF Legacy/Classic as being in 'pure maintenance'.

**Comment by azoitl** [comment]
Hi Pierre-Charles,

thanks a lot for sharing your concerns with us. As pointed out I really hope that projects like GMF Runtime and Sirius are closely monitoring what we do. But I also hoped that fixes and workarounds that is currently in the repositories of the the projects you are mentioning will also be upstreamed to GEF itself. 

In the current point I think we are mostly getting to know the code base and start minor changes. Therefore I think it is to early for starting a full fledged roadmap.

Please be ensured that at least for me the stability of GEF Classic is a major objective. I'm myself working a GEF Classic based tool which relies on the stability of the GEF API. We already added the api base line checks to inform us early if we mess that. But at that point I at least have no plans for introducing breaking changes. 

Regarding issue #21 I may have not well spelled my intention. My intention was not to remove deprecated APIs itself but I wanted to clean-up the internal use of deprecated APIs. This should not be visible from the outside but help to reduce the number of warnings of the GEF Classic code and help to make the existing code base more maintainable.

I hope my message addresses your concerns, which I also have. Thanks for any early feedback if go in the wrong direction.

**Comment by vogella** [comment]
Hi Pierre-Charles,

platform requires Java 11 since a while, so hopefully moving GEF to Java 11 will not break anything for GMF or Sirius. We are still early in the process and the currently plan it to make the build work again, setup signing, setup baseline validation, create a "latest" update site, fix tests etc. 

Once this is done it would be great if GMF and Sirus could setup an additional build using the latest update site of GEF to identify breaking changes as early as possible. 

After that I hope that feature work will start, AFAIK the current plan is to do this API compliant. If API breakage feels necessary we will discuss it with you and other adaptors.

Does this sound good to you?

**Comment by vogella** [comment]
We have a "latest" update site now. @pcdavid to avoid unexpected breakage for GMF and Sirius I would be great if you could setup a build job which validated your tooling against this version, this should help identifying issues early in the process.

I close this issue, as it seems that nothing is open here, please reopen or open new issues if you see still problems.

**Comment by vogella** [comment]
Update site http://download.eclipse.org/tools/gef/classic/latest

**Comment by pcdavid** [comment]
> Update site http://download.eclipse.org/tools/gef/classic/latest

Thanks. We have a [canary target platform](https://git.eclipse.org/c/sirius/org.eclipse.sirius.git/tree/releng/org.eclipse.sirius.targets/sirius_canary.targetplatform) which builds against the latest "nightlies" of everything. It's broken at the moment because of the recent changes in Orbit, but I'll update the "GEF-Legacy-3.11" we have location to point to that instead.

**Comment by vogella** [comment]
Thanks @pcdavid
