### ISSUE TITLE
Fix test errors 

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#28]
Jenkins shows failing test. See https://ci.eclipse.org/gef/job/gef-classic-master/3302/

[Testergebnis](https://ci.eclipse.org/gef/job/gef-classic-master/3302/testReport/) (5 fehlgeschlagene Tests / ±0)
[org.eclipse.draw2d.test.TextFlowWrapTest.testNestedInlineFlows](https://ci.eclipse.org/gef/job/gef-classic-master/3302/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testNestedInlineFlows/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testHardWrapping](https://ci.eclipse.org/gef/job/gef-classic-master/3302/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testHardWrapping/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testInlineFlow](https://ci.eclipse.org/gef/job/gef-classic-master/3302/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testInlineFlow/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testTruncatedWrapping](https://ci.eclipse.org/gef/job/gef-classic-master/3302/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testTruncatedWrapping/)
[org.eclipse.draw2d.test.TextFlowWrapTest.testSoftWrapping](https://ci.eclipse.org/gef/job/gef-classic-master/3302/testReport/junit/org.eclipse.draw2d.test/TextFlowWrapTest/testSoftWrapping/)

@azoitl can you have a look?

**Comment by azoitl** [comment]
Yes for sure.

**Comment by azoitl** [comment]
I spent some time debugging this. If I understand correctly this issue is coming from the FlowUtilities in the lines 324-333. Fixing it there needs a bit more time. Line breaking rules are never easy to handle.

But it looks like these tests should have failed also before. So I'm not sure if this is now expected behavior.

**Comment by vogella** [comment]
Are these tests requiring a Display? Maybe the virtual display is not configured correctly?

**Comment by azoitl** [comment]
As far as I understood the failing tests create draw2d figures which are not added to anything. And also from debugging the failing testcases I see that there is a string array `"a abc", "-def"` with the expected result that the text flow is inserting a newline between `-`and `def`. Which  is not happening. As the other lines are correctly separated I still think it is an issue of the line breaking algorithm. 

Do we know if these test where working before?
