### ISSUE TITLE
Broken TextFlowWrapTest due to com.ibm.icu.text.BreakIterator

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#289]
The TextFlowWrapTest is currently marked as ignored, due to unstable failures in `testNestedInlineFlows()`, `testHardWrapping()` and `testInlineFlow()`. 

After further looking into it, I came to the conclusion that they are not unstable, but rather that they fail because the BreakIterator used in FlowUtilities doesn't behave the way as expected by the test.

To reproduce:
- Remove the Ignore annotation from the test class
- Run the tests, 3 test cases should fail
- Go to FlowUtilities
- Switch to javax.text.BreakIterator
- Run the tests again, all should pass now

Looking at the history, we switched to the javax BreakIterator with 6b6eba6093e4f62536bec7d2f198aa961765cfa9 but then reverted back to the com.ibm.icu BreakIterator with 9e560cf2b2d63e03d6721a9346895d4ce44471f2, due to #116 

Given that the test was written for the com.ibm.icu BreakIterator but now fails, even though we continue to use the same class, makes me believe that something in the com.ibm.icu implementation has changed in a way that was not intended by the original author.

In general, there are two options on how we can approach this issue:

1) Accept the new behavior as the "correct" state, meaning we have to adjust the unit test accordingly.
2) Switch back to the javax BreakIterator under the assumption that this is how the iterator is supposed to behave.
3) ~~Continue to ignore those failing test cases~~

Given that we explicitly want the current behavior, I'm leaning towards the first solution. What are your thoughts?

**Comment by vogella** [comment]
If possible move away from using ICU. We in platform want to get rid of it (we just having not enough people to look as the remaining uses)

**Comment by vogella** [comment]
Reason for moving away from ICU is that it is not kind of huge and not actively developed

**Comment by ptziegler** [comment]
The primary concern is how this changed line-break behavior would affect downstream projects. I think @Phillipus brought it up some time ago regarding https://github.com/archimatetool/archi

From what I understand, there are "[bugs](https://unicode-org.github.io/icu/userguide/icu4j/faq.html#why-did-you-bother-to-rewrite-breakiterator-wasnt-the-old-version-working)" inside the Java BreakIterator implementation (at least according to the ICU4J team), which they fixed in their own implementation. Which is why we a different break behavior depending on which class we use.

I'm usually in favor of getting rid of additional dependencies but as mentioned earlier, this may break backwards compatibility. So the question is: Would we be willing to accept that?
And if so, should we consider a way for users to inject their own implementation?

**Comment by azoitl** [comment]
As I did some experiments when @Phillipus brought up #116 I'm really not sure. Getting rid of dependencies is always a thing that I normally find good. On the other side the output of Java's BreakIterator is really partly a bit strange. Currently I'm not a big user of that so I think I should kept my mouth shut. But maybe the approach of allowing clients to provide own break handling code could be a solution that helps us in maintainability and gives users of GEF Classic the flexibility of using the right BreakIterator.

**Comment by ptziegler** [comment]
I'll try to have a look at this issue for the upcoming development cycle. 

I assume extension points are not an option, given that a dependency to eclipse.platform is undesirable for Draw2D. So the alternative would be an OSGi service.

My current idea is to create a new interface, which can be implemented by clients. If no implementation is found, we fall back to an internal implementation using javax.text.BreakIterator.
