### ISSUE TITLE
Configure PR validation with Jenkins

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#30]
We should setup PR validation with Jenkins. 

Anyone knows how to do this?

**Comment by pcdavid** [comment]
Not tested it (yet), but see https://wiki.eclipse.org/Jenkins#GitHub_integration

**Comment by vogella** [comment]
Thanks. @pcdavid I'm happy with "only" using GH actions for validation so I close this for now, Jenkins seems less stable for platform so I do not plan to spend time on this one.
