### ISSUE TITLE
Host an Oomph Setup for GEF Classic?

### ISSUE THREAD

**Issue by merks** [eclipse/gef-classic#308]
Currently there is already a fully functional Oomph setup for GEF classic hosted here:

https://github.com/eclipse-oomph/oomph/blob/master/setups/interim/GEF.setup

It would be better hosted in the repository itself.

You can already try it out now like this in the instalelr:

![image](https://github.com/eclipse/gef-classic/assets/208716/9caca525-26aa-4b47-a7f7-b58f779ae9eb)

![image](https://github.com/eclipse/gef-classic/assets/208716/4bf67383-dcca-48ae-92fd-1ba2ce7a6b8b)

It creates an IDE with working sets like this:

![image](https://github.com/eclipse/gef-classic/assets/208716/b0c67540-52f3-42d7-afde-174be2c55045)

There appears to be no 100% appropriate place in the clone in which to host the .setup files.  I could put it in the root of the clone. Or is there a better place we could create to put them (the project setup and the to-be-written configuration setup)?

**Comment by ptziegler** [comment]
I would just host them in their own project. Perhaps in `org.eclipse.gef.setup`, similar to how the baseline target definitions are stored in `org.eclipse.gef.baseline`?

I wanted to mention how parts like the baseline didn't work in the setup, but it seems like you were already ahead of me again. :sweat_smile:

**Comment by merks** [comment]
The setups are committed and there is a link here now:

https://github.com/eclipse/gef-classic/blob/master/CONTRIBUTING.md#set-up-a-development-environment

The setup creates a .project file for the root, but the filters ensure that nested project content are not duplicates and the .project file itself is ignored (not in git):

![image](https://github.com/eclipse/gef-classic/assets/208716/768a5966-245d-4d54-b2da-fd1303d94b2b)

This allows the setups to be visible in a project, as well as the promotion pom.xml
