### ISSUE TITLE
Weird behavior in Zest Structured Graph Viewer

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#321]
I'm currently looking at some of the raw-type warnings in the Zest component and noticed the following oddity which I have a hard time wrapping my head around:

Whenever we remove a node from a viewer, we also remove the connections from the algorithm.
https://github.com/eclipse/gef-classic/blob/c2be6d8b4c9d47657bc8cfda35bf8835523277e9/org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/AbstractStructuredGraphViewer.java#L697-L710

Those relationships are expected to implement the [LayoutRelationship](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutRelationship.java) interface. So far so good.

https://github.com/eclipse/gef-classic/blob/c2be6d8b4c9d47657bc8cfda35bf8835523277e9/org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutAlgorithm.java#L123-L125

However, those source/target connections should be of type [GraphConnection](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java), which doesn't implement this interface.

Otherwise checks such as here in the dispose() method would fail with a ClassCastException.

https://github.com/eclipse/gef-classic/blob/c2be6d8b4c9d47657bc8cfda35bf8835523277e9/org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java#L199-L223

I'm not sure what the expectation is here. I assume that this "works", as long as we don't iterate over the list of connections but in any other case it would break.

**Comment by ptziegler** [comment]
Something similar is the case for GraphNodes...

I would expected that GraphNode implements LayoutEntity and that GraphConnection implements LayoutRelationship.

**Comment by azoitl** [comment]
Maybe you could have a look at intermediate versions of Zest as pointed out be Fabian Steeg in this mailing list post: https://www.eclipse.org/lists/gef-dev/msg02188.html

**Comment by ptziegler** [comment]
Hm... in short, this is an oversight. Up until 69869b95ece55b38d91b05c445683d0cd4cf88c3, GraphConnection used to implement LayoutRelationship. So this part has been broken for the past 16 years :sweat_smile:.

> Maybe you could have a look at intermediate versions of Zest as pointed out be Fabian Steeg in this mailing list post: https://www.eclipse.org/lists/gef-dev/msg02188.html

Weirdly enough, there the problematic part doesn't  show up...
```
public void removeNode(Object element) {
	GraphNode node = (GraphNode) nodesMap.get(element);

	if (node != null) {
		// remove the node and it's connections from the model
		node.dispose();
	}
}
```

But I can have a look whether it can be reintegrated. At a glance, I can already see this... yikes.

```
Require-Bundle: org.eclipse.ui,
 org.eclipse.core.runtime,
 org.eclipse.jdt.core,
 org.eclipse.jdt.junit,
 org.eclipse.debug.core,
 org.junit4;resolution:=optional,
 org.eclipse.pde.core,
 org.eclipse.ui.ide,
 org.eclipse.jdt.ui,
 org.eclipse.jdt.launching,
 org.eclipse.debug.ui,
 org.eclipse.zest.dot.core;visibility:=reexport,
 org.eclipse.help,
 org.eclipse.help.ui,
 org.eclipse.help.appserver;resolution:=optional,
 org.eclipse.help.webapp,
 org.eclipse.jdt.launching.macosx;resolution:=optional,
 org.eclipse.mylyn.wikitext.ui;resolution:=optional,
 org.eclipse.mylyn.wikitext.textile.core;resolution:=optional,
 org.eclipse.mylyn.wikitext.textile.ui;resolution:=optional,
 org.eclipse.xtext.ui;bundle-version="2.0.0",
 org.eclipse.xtext.ui.shared;bundle-version="2.0.0",
 org.eclipse.ui.editors,
 org.antlr.runtime;bundle-version="3.2.0",
 org.eclipse.xtext.builder;bundle-version="2.0.0",
 org.eclipse.equinox.ds,
 org.eclipse.core.filesystem;bundle-version="1.3.100"
```

**Comment by ptziegler** [comment]
Perhaps we can simply do without the dot components :thinking:

**Comment by azoitl** [comment]
Yes the dot stuff should definitely be avoided or moved to an own feature. Because this pulls in a lot of stuff. This we also discussed on the mailing list.

**Comment by ptziegler** [comment]
I forgot that this was fixed with https://github.com/eclipse/gef-classic/pull/395
