### ISSUE TITLE
Oomph setup pulls in GEF FX dependencies

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#352]
One thing I noticed while working on the online help is that the workspace seems to also contain the artifacts from GEF FX.

![image](https://github.com/eclipse/gef-classic/assets/70652978/2297b375-c297-4246-a49e-d1d3290e86f9)

This was confirmed by a quick plugin-search, indicating that those bundles are part of the dependency set that is calculated the modular targlet.

![image](https://github.com/eclipse/gef-classic/assets/70652978/fc2082e4-8e75-4abe-af17-375308ac3128)

While not a critical problem (yet), it's probably not a good idea to mix GEF Classic and GEF FX.

Given that you're far more knowledgeable about the inner workings of Oomph @merks , do you know of a a view or another easy way to see the dependency tree that is calculated by the tool or do I have to remotely debug it, to figure out what's going on?

**Comment by merks** [comment]
I didn't realize that the set of IUs between GEF FX and GEF Classic are not unique.  Fortunately I could just remove the one repository that contains GEF FX to eliminate the issue.
