### ISSUE TITLE
Figure#setToolTip can lead to recursion

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#357]
In fd75841fd7e0638c18827f203257e504536fb15e this method was changed from:

```java
public void setToolTip(IFigure f) {
    if (toolTip == f) {
	    return;
    }
    toolTip = f;
}
```

to:

```java
public void setToolTip(IFigure f) {
    if (getToolTip() == f) {
	    return;
    }
    toolTip = f;
}
```

This can cause infinite recursion if, like me, you over-ride `getToolTip` to lazily create a ToolTip:

```java
public IFigure getToolTip() {
    ToolTipFigure toolTipFigure = (ToolTipFigure)super.getToolTip();
    
    if(toolTipFigure == null) {
        toolTipFigure = new ToolTipFigure();
        setToolTip(toolTipFigure);
    }

    return toolTipFigure;
}
```

`getToolTip` calls `setToolTip` which calls `getToolTip` which calls `setToolTip`...

@azoitl I think this is the reason for the original code.

**Comment by azoitl** [comment]
Oh. Yes that is bad. As written in my commit message I wanted to reduce warnings on deprecated code usage. And I tried to be rather sensitive here and not call methods which have side effects but I totally missed that use case. 

I guess in the end we will need to start to remove the deprecated entities at one point (e.g., in this specific case turn the field private).

Will change it back.

**Comment by Phillipus** [comment]
> Will change it back.

Thanks!

> I guess in the end we will need to start to remove the deprecated entities at one point (e.g., in this specific case turn the field private).

Agreed.
