### ISSUE TITLE
What's the best practice for editing source files?

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#359]
If I make one small change to a source file, say just one line, the whole file is auto-formatted because of the formatting rules in the local `*.prefs` files. This makes it hard to see the single change amongst all the others.

Should one commit a "tidy formatting" commit first?

**Comment by azoitl** [comment]
I have formatted all files by now. However I enabled some auto-clean-ups. Sofar @ptziegler and I have applied some single clean-ups to all of the files to reduce the changes. However it is a lot of effort to harmonize the on save clean-ups with the code clean-ups. At least I didn't find an easy way. Otherwise I would be fully in for auto-clean-up of all files first.

**Comment by Phillipus** [comment]
I'm not sure I understand. Are you saying you don't get all the formatting changes when you save a file? Or that you somehow ignore them?

**Comment by azoitl** [comment]
sorry for not expressing myself clearly. What I wanted to say is that I reformatted all source code according to the rules already quite some time ago.  However in addition to reformatting I enabled some auto code clean-up. This is for me more then just formatting (e.g., using ranged for loops or replace with lambdas). 

The latter is currently not applied to all files yet and this may result in some additional changes. However the biggest of these (inserting  { }) should be done to all. 

If you still get a lot of formatting changes then I may missed something.

**Comment by Phillipus** [comment]
> If you still get a lot of formatting changes then I may missed something.

I simply change one line in a file, then save it, and lots of formatting is applied to the file.

**Comment by azoitl** [comment]
strange. Can you share a diff or tell me the file you tried so that I can try on my machine.

**Comment by Phillipus** [comment]
I've figured it out.

I use a custom Java formatter in Eclipse's settings - Java -> Code Style -> Formatter. When I saved a file it was applying these settings. If I change the formatter to "Eclipse [built-in]" it's OK.

**Comment by vogella** [comment]
Maybe we should set the formatter in the project options?

**Comment by Phillipus** [comment]
> Maybe we should set the formatter in the project options?

Is this possible without messing up the existing options in the `.settings/*.prefs` files? @azoitl

**Comment by azoitl** [comment]
> > Maybe we should set the formatter in the project options?
> 
> Is this possible without messing up the existing options in the `.settings/*.prefs` files? @azoitl

let me try.
