### ISSUE TITLE
Error when installing Eclipse GEF Classic.

### ISSUE THREAD

**Issue by BrandonBlackwell** [eclipse/gef-classic#369]
When installing Eclipse GEF Classic via "Install New Software" I receive this error:

`An error occurred while collecting items to be installed session context was:(profile=_home_..._eclipse_java-2023-09_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=). No artifact repository available. noArtifactRepositoriesAvailable`

I currently have Eclipse 2023-09 installed.
Happens on both Windows 10 and Redhat Linux.

Steps taken to install Eclipse GEF Classic:

1. Fresh install of Eclipse 2023-09
2. Download the zip from https://download.eclipse.org/tools/gef/classic/release/3.18.0/
3. Unzip in dropins
4. Install New Software > add > archive > .jar
5. Check the box for GEF features ONLY
6. Uncheck "contact all updatesites" (Because this is an offline installation)
7. Next > Finish
8. Error happens on the download.

**Comment by ptziegler** [comment]
Out of curiosity, is there a reason that you used the installation dialog when you've already unzipped the archive into the dropins folder?

The way this folder should work is that it automatically [installs](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fp2_dropins_format.html) all artifacts that are contained by it during startup, meaning there should be no need for any additional steps.

> Install New Software > add > archive > .jar

Which jar do you mean? The content.jar?
Because if I try to reproduce this behavior, I get the following dialog, telling me that GEF has already been installed.

![image](https://github.com/eclipse/gef-classic/assets/70652978/b8affe1f-21b5-4622-8ad8-a858f7c7ee56)

**Comment by BrandonBlackwell** [comment]
Out of curiosity, is there a reason that you used the installation dialog when you've already unzipped the archive into the dropins folder?
- Yes, unzipping into the dropins folder and restarting doesn't install Eclipse GEF. Installing via installation dialogue gets me further into the installation process. There are some plugins that I've gotten to work by installing via dropins and installation dialogue and some via dropins alone. I'm simply trying different methods to get things working.

Which jar do you mean? The content.jar?
- content.jar

This is the correct version of Eclipse. It doesn't have GEF. 
https://www.eclipse.org/downloads/packages/release/2023-09/r/eclipse-ide-java-developers

**Comment by BrandonBlackwell** [comment]
In my case, I'm doing an offline install so, I'll have to mirror the repo. Let me give this a try.

**Comment by ptziegler** [comment]
> I'll have to mirror the repo. Let me give this a try.

If you have the Eclipse executable, you can download and zip the update site by hand:
https://stackoverflow.com/questions/1371176/downloading-eclipse-plug-in-update-sites-for-offline-installation

So in the case of GEF 3.18, the command line calls would look something like this:
> eclipsec.exe -application org.eclipse.equinox.p2.metadata.repository.mirrorApplication -source https://download.eclipse.org/tools/gef/classic/release/3.18.0 -destination ./gef-classic

> eclipsec.exe -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source https://download.eclipse.org/tools/gef/classic/release/3.18.0 -destination ./gef-classic

**Comment by merks** [comment]
Strange. The milestone zip isn’t empty 

https://download.eclipse.org/justj/?file=tools/gef/classic/milestone/S202401101332

I’ll look at how best to repair it.

**Comment by merks** [comment]
It will need a little TLC tomorrow.

**Comment by BrandonBlackwell** [comment]
Mirrored the repo and went through the same process, unfortunately, I received the same error message. 

`An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No artifact repository available.
noArtifactRepositoriesAvailable`

I'm going to just install the normal way and copy the entire eclipse directory and send to the offline environment. Hopefully that works.

**Comment by merks** [comment]
Note that to mirror you have to run the application twice. Once for the content metadata and once for the artifact metadata. It sounds like you only did the former.

**Comment by BrandonBlackwell** [comment]
I ran commands for both the metadata and artifacts:

`eclipsec.exe -application org.eclipse.equinox.p2.metadata.repository.mirrorApplication -source https://download.eclipse.org/tools/gef/classic/release/3.18.0 -destination ./gef-classic`

`eclipsec.exe -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source https://download.eclipse.org/tools/gef/classic/release/3.18.0 -destination ./gef-classic`

**Comment by ptziegler** [comment]
> The "gef-classic" directory has features, plugins, artifact.jar, and content.jar
> From there I installed through the installation dialogue using "content.jar" and receive the same error.

If you have both the metadata and artifacts, you can also just point to the folder (via the "Local..." button), rather than the "content.jar".

![image](https://github.com/eclipse/gef-classic/assets/70652978/1c23655e-8540-4a08-918b-61fde7339da7)

It should now also be possible to install GEF via the dropins folder by simply copying the plugins/features folder from your local mirror (without the artifacts.jar/content.jar).

**Comment by merks** [comment]
The TLC has been applied:

![image](https://github.com/eclipse/gef-classic/assets/208716/03a6fc07-5180-401c-8bd3-e97f3993ee06)

The [p2.manager](https://eclipse.dev/justj/?page=tools) will now properly mirror the repository to the local host when it needs to make a update site archive.  So I just needed to delete bad files:

![image](https://github.com/eclipse/gef-classic/assets/208716/e273c873-291d-41a7-94a4-cf89e4ae9f93)

and do a nightly build to produce proper new the update site archives.

**Comment by ptziegler** [comment]
Awesome! Thank you a lot. 😄
