### ISSUE TITLE
Anything to migrated from the Eclipse wiki to Markdown

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#370]
I'm currently migrating Eclipse platform wiki to markdown. Do you guys have any wiki pages which you would like to keep? Same for Windowbuilder @ptziegler, if you have some wiki pages you like to keep just let me know. I have now a bunch for Dart scripts which do most of the work....

**Comment by ptziegler** [comment]
I've only found a single entry for the WindowBuilder related to Nebula, but I believe that section is -in most parts- already covered by our documentation.

![image](https://github.com/eclipse/gef-classic/assets/70652978/a8f916c0-42b0-4224-aa3a-c7a6b6a5db51)

For GEF (Classic), the following entries seem to be worth saving. While incomplete, it goes into a lot more detail than our help does. @azoitl Do you know of any other resources that should be preserved?

https://wiki.eclipse.org/GEF_Description
https://wiki.eclipse.org/GEF_Description2

**Comment by vogella** [comment]
Thanks @ptziegler saw your post a bit late. I will now migrate your pages.

**Comment by azoitl** [comment]
@vogella @ptziegler I also wanted to reply for quite some time. Somehow I forgot. I just checked all Wiki pages with GEF in the title appart the two very good pages that @ptziegler mentioned and that @vogella already converted I didn't find any other pages that are not already in our github wiki.

**Comment by vogella** [comment]
https://github.com/eclipse/gef-classic/blob/master/docs/GEF_Description.md
https://github.com/eclipse/gef-classic/blob/master/docs/GEF_Description2.md

created and wiki updated with links to the new documentation.

**Comment by ptziegler** [comment]
Sorry, I got a little distracted by those weird build errors.
Thank you for your work! It didn't even occur to me that there was still something on the wiki.

**Comment by vogella** [comment]
No worries @ptziegler thanks for looking into the build issues
