### ISSUE TITLE
Change from #347 break the FanRouter functionality

### ISSUE THREAD

**Issue by wiresketch** [eclipse/gef-classic#383]
Change #347 that is seemingly only cosmetic, changes the code in FanRouter handleCollision method from:
```
		if (index % 2 == 0) {
			bendPoint = new Point(midPoint.x + (index / 2) * (-1 * ySeparation),
					midPoint.y + (index / 2) * xSeparation);
		} else {
			bendPoint = new Point(midPoint.x + (index / 2) * ySeparation,
					midPoint.y + (index / 2) * (-1 * xSeparation));
		}
		if (!bendPoint.equals(midPoint))
			points.insertPoint(bendPoint, 1);
```
to

```
		if (index % 2 == 0) {
			bendPoint = new Point(midPoint.x + (int) ((index / 2.0) * -1.0 * ySeparation),
					midPoint.y + (int) ((index / 2.0) * xSeparation));
		} else {
			bendPoint = new Point(midPoint.x + (int) ((index / 2.0) * ySeparation),
					midPoint.y + (int) ((index / 2.0) * -1.0 * xSeparation));
		}
		if (!bendPoint.equals(midPoint)) {
			points.insertPoint(bendPoint, 1);
		}
```

This breaks the connection drawing in the application that I'm developing. Here's a simple visual example.

Before:
![before](https://github.com/eclipse/gef-classic/assets/906911/c64dfb29-1786-4ab8-967f-06758b68aa86)

After:
![after](https://github.com/eclipse/gef-classic/assets/906911/c9acfe47-f94e-4f02-beb3-3b206f350f70)

Clearly the new code change is not equivalent to the old one. The effect is that before the condition after the bendPoint calculation was false, but in the changed code it's calculated as true.

**Comment by wiresketch** [comment]
Yes, this is what causes the problem.

**Comment by azoitl** [comment]
As I broke it I'll provide a fix. Will do that right after the repo is ready for 3.20

**Comment by ptziegler** [comment]
> As I broke it I'll provide a fix. Will do that right after the repo is ready for 3.20

I already had a look at it yesterday and I think the easiest way is to simply revert the change and use a PrecisionPoint, to get rid of the deprecation warning. See #385
