### ISSUE TITLE
Relax demands on PaletteContainer getChildren() method

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#401]
The method should be adapted to:

```
public List<? extends PaletteEntry> getChildren() {
	return children;
}
```

This currently leads to compilation errors in our workspace because of custom tool entries.

**Comment by sratz** [comment]
While #403 has resolved compilation failures on the extender side, this has now introduced compilation failures on the consumer side:

```
17:20:30 [ERROR] /home/jenkins/workspace/nightly_master_platform_2024-06/git/<snip>/LayoutPage.java:[522] 
17:20:30 [ERROR] 	List<PaletteEntry> children = LayoutPage.this.paletteRoot.getChildren();
17:20:30 [ERROR] 	                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:20:30 [ERROR] Type mismatch: cannot convert from List<capture#1-of ? extends PaletteEntry> to List<PaletteEntry>
```

**Comment by ptziegler** [comment]
The problem is that this may introduce compilation failures either way. With the previous implementation we ended up with errors in our application instead.

The reason why wildcards are used is because it allows for type-casting. e.g. (List\<PaletteEntry\>) in your case or (List\<CustomPaletteEntry\>) in our case. This is not possible, otherwise.

**Comment by azoitl** [comment]
As I experienced that also in the RCP I'm mostly working on (i.e., [4diac IDE](https://github.com/eclipse-4diac/4diac-ide)) it was always when we had used unsafe casts. So the new code is much more explicit and allows to write more correct client code while at the same time gives the possibility that children provide more specialized versions.
