### ISSUE TITLE
Problem to unreference EditParts

### ISSUE THREAD

**Issue by pdeville2** [eclipse/gef-classic#417]
Hello,

In our tools (Papyrus) we have some memory leak issues (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=583119).

In the issue #391 we discuss about releasing EditPolicies and we conclude the we should first release EditPart then EditPolicies should release automatically. However I still having some issues with this since EditPart are autoreferencing, an editPart A reference a child editPart B via the _children_ attribut and the B reference A via _parent_ attribut. If one element of this chain is still referenced nothing can be garbage collected.

Do you think I miss something obvious? I suppose that if A and B are not referenced anymore by others then it should be garbage collected, but is often hard to make sure that all EditPolicies are referenced.

I would like to propose to use WeakReference on the _parent_ attribut since a child should not live anymore if its parent is dead (see https://github.com/pdeville2/gef-classic/commit/4f6bf326d95f515a62b448cb35bea9e5249acc63).

What do you think about this proposal?

I have mostly the same issue with EditPart and EditPolicy, EditPart reference EditPolicy via _policies_ attribut and EditPolicy reference the edit Part via _host_.

**Comment by azoitl** [comment]
Java Garbage collectors are for many years very well capable of handling these kind of circular dependencies (see for example this article: https://www.baeldung.com/java-gc-cyclic-references. Especially the new Garbage collectors of the later Java versions got really really good. 

Therefore I still believe that there is something in your editors that is not correctly releasing the editparts. I have diagrams with thousands of EditParts and don't see that problem. 

I also don't think that WeakReference will help here. I even think in the worst case they can break things. As it is written in the documentation of WeakReference they should be used when the object can easily be recreated. We can't do that.

**Comment by ptziegler** [comment]
From what I remember, reachability is calculated starting from GC root. Which means that the _parent_ and _child_ edit parts are not destroyed, because one is still strongly reachable via a third object.

But to avoid stalling the discussion, I think one of the two approaches might be feasible:
1) Use the [Memory Analyzer](https://eclipse.dev/mat/) to create a heap dump, to see which objects are keeping the edit parts alive.

2) Test Papyrus with a local version of GEF containing those soft references and see whether the memory problems still exist.

**Comment by pdeville2** [comment]
Thanks for your responses and sorry to have insisted,

Globally I know that it means that one of my editPart of editPolicy are still reference elsewhere. 

@ptziegler I already use a analyzer tool (VisualVM) and I already tried my patch in local and it effectivly release editParts and most of the EditPolicies

I still understand you point of view, the WeakReference is not really a solution but rather a workaround however we may not be alone in this case.

**Comment by azoitl** [comment]
@pdeville2 I would be happy to have a look on your memory analyzer output. Would you like to send it to me. Sometimes a second pair of eyes can help.

**Comment by pdeville2** [comment]
Thanks for your help @ptziegler and @azoitl, I think I found part of my problem.

**Comment by azoitl** [comment]
> Thanks for your help @ptziegler and @azoitl, I think I found part of my problem.

Happy to hear that and that we could be of help. Any lessons learned that could be of interest to other GEF Classic or GMF users?
