### ISSUE TITLE
Ruler guides are broken in  GEF 3.19.0.202402212051

### ISSUE THREAD

**Issue by wiresketch** [eclipse/gef-classic#418]
When using ruler guides the following exception is constantly being logged and ruler guides do not work:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.eclipse.gef.internal.ui.rulers.RulerLayout.getConstraint(org.eclipse.draw2d.IFigure)" is null
	at org.eclipse.gef.internal.ui.rulers.RulerLayout.layout(RulerLayout.java:55)
	at org.eclipse.draw2d.Figure.layout(Figure.java:1201)
	at org.eclipse.draw2d.Figure.validate(Figure.java:2060)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.draw2d.Figure.validate(Figure.java:2061)
	at org.eclipse.draw2d.Viewport.validate(Viewport.java:378)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.draw2d.Figure.validate(Figure.java:2061)
	at org.eclipse.draw2d.DeferredUpdateManager.performValidation(DeferredUpdateManager.java:225)
	at org.eclipse.draw2d.DeferredUpdateManager.paint(DeferredUpdateManager.java:167)
	at org.eclipse.draw2d.LightweightSystem.paint(LightweightSystem.java:202)
	at org.eclipse.draw2d.LightweightSystem.lambda$0(LightweightSystem.java:110)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3927)
	at org.eclipse.swt.widgets.Scrollable.gtk_draw(Scrollable.java:365)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:506)
	at org.eclipse.swt.widgets.Canvas.gtk_draw(Canvas.java:174)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2482)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6883)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6162)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1598)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
```

The issue is introduced in commit 4635985b7045db7bd80758387c7c360aa7eda305 from Dec 30, 2023 which apparently only modernizes code, but breaks the ruler functionality. The problem is with the change in XYLayout where constraints are forced to be Rectangles. Since setConstraint method takes an object the change adds an instanceof check and silently rejects all other types of constraints:

```
	public void setConstraint(IFigure figure, Object newConstraint) {
		super.setConstraint(figure, newConstraint);
		if (newConstraint instanceof Rectangle rect) {
			constraints.put(figure, rect);
		}
	}
```

Previously this method looked like this:

```
	public void setConstraint(IFigure figure, Object newConstraint) {
		super.setConstraint(figure, newConstraint);
		if (newConstraint != null)
			constraints.put(figure, newConstraint);
	}
```

This change breaks RulerLayout class which is a subclass of XYLayout and which uses Integer constraints instead of Rectangle.

This issue is really critical since I couldn't not find a way to add a workaround in my app. The fix could either revert this change, or perhaps make RulerLayout inherit directly from AbstractLayout to remove the dependency on XYLayout.

I am really worried about all this changes lately. Code modernization is nice, but doing it just for the sake of it feels unnecessary to me. On the other hand this is the second breaking change I find, and this just in the code I use, so this trend really worries me.

**Comment by azoitl** [comment]
@wiresketch first of all I totally understand your concern and I'm also not happy about the situation. I'm really trying my best to not produce situations like the one you found now twice. On the other hand we have the situation that GEF Classic has a lot of dangerous code  that can lead in special situation to severe issues. Also we have performance issues and would like to get new features in (e.g., #261).  That is one of the reasons I spend my time on cleaning the code. 

Coming back to the problem you found. After looking at the code I strongly belive that RulerLayout should never have inherited from XYLayout. If you agree I would change that to AbstractLayout as you suggest and fix the problems we have here.

**Comment by azoitl** [comment]
Thx this helps. I tried and in my RCP this solves the problem. I would have two questions where I would be happy to get feedback:

1. I think `setConstraint should check if the `newConstraint` is an Integer, but what to do if it is not?
2.  `RulerLayout.getOrigin()` is never directly called and there is no cast to XYLayout. So I think we could remove that.

**Comment by wiresketch** [comment]
1. I strongly believe that setConstraint method should throw ClassCastException instead of silently ignoring constraints of other types. This way the code that uses RulerLayout incorrectly can fail and then be directly identified. The silent solution will make problems resurface in other parts of the code, but in those cases it will be much more difficult to identify the original issue. For example to identify the current issue I had to resort to debugging to locate the original cause.
2. You are right about getOrigin method. I missed the fact that it's not inherited from AbstractLayout.

**Comment by azoitl** [comment]
ad 1) you have a good point here. Will follow that.

**Comment by ptziegler** [comment]
A few cents from my side:

1) I generally agree that an exception should be thrown when an invalid constraint is used. The JavaDoc even explicitly says `The constraints can only be of type Rectangle. But wouldn't an IllegalArgumentException be more appropriate?

An more generally, how difficult do you two think it would be to create a small ruler example? It's apparently used in the Logic example, but I have yet to figure out how to make it show up exactly.

I think a large part of this problem is caused by our abysmal test coverage. So whenever such regressions do show up, I'd like to include a reproducer it to our automatic tests.

![image](https://github.com/eclipse/gef-classic/assets/70652978/c308c263-5fd8-4136-b521-599731e38917)

**Comment by azoitl** [comment]
> A few cents from my side:
> 
>     1. I generally agree that an exception should be thrown when an invalid constraint is used. The JavaDoc even explicitly says `The constraints can only be of type Rectangle. But wouldn't an IllegalArgumentException be more appropriate?

That seems for me even better.

> 
> An more generally, how difficult do you two think it would be to create a small ruler example? It's apparently used in the Logic example, but I have yet to figure out how to make it show up exactly.
> 
> I think a large part of this problem is caused by our abysmal test coverage. So whenever such regressions do show up, I'd like to include a reproducer it to our automatic tests.

I totally agree. And I'm really bad at testing.  I fear the ruler would need a full fledged GEF Classic editor to be tested. Waht I can try is to see how we get the ruler shown in the Logic editor. Which I think would anyhow be a good idea.

**Comment by wiresketch** [comment]
@ptziegler From the looks of it the logic example should have a menu entry for toggling the ruler visibility.

**Comment by ptziegler** [comment]
> From the looks of it the logic example should have a menu entry for toggling the ruler visibility.

Thanks! I found it.

![image](https://github.com/eclipse/gef-classic/assets/70652978/cff20596-ed27-453a-a225-b1b17f01dc4a)

**Comment by azoitl** [comment]
There I wouldn't have searched for it.
