### ISSUE TITLE
Make AbstractTool's accessibleStep mechanism accessible for subclasses

### ISSUE THREAD

**Issue by lredor** [eclipse/gef-classic#426]
Currently, it's not possible to use the methods "accStepReset()", "accStepIncrement()" and "accGetStep()" in AbstractTool subclasses. The goal of this issue is to make these methods protected to allow its use in a subclass.

The final goal is to use them in a subclass of Sirius for issue [359](https://github.com/eclipse-sirius/sirius-desktop/issues/359).

**Comment by azoitl** [comment]
In general I'm fine with this change. However quickly reading over the Sirius bug report I wanted to ask if not more of this problem should be solved on GEF Classic side? 


Also please note for API changes you need to add documentation to the now API functions including the `@since 3.18` tag.
