### ISSUE TITLE
Unable to clone the gef repository

### ISSUE THREAD

**Issue by lak-proddev** [eclipse/gef-classic#462]
I am unable to clone either with the command line or Eclipse git tools. Please check
![image](https://github.com/eclipse/gef-classic/assets/39690425/200aa204-dc7c-4e87-927f-f6c7de6fc75c)

**Comment by merks** [comment]
The Oomph setup, which uses Eclipse EGit under the covers,  worked for me just now:

![image](https://github.com/eclipse/gef-classic/assets/208716/f1cebbc0-e3db-478b-8736-04079cad4142)

Maybe is was a temporary network problem?  Maybe there is something funky about your network.  Is a firewall involved?

**Comment by azoitl** [comment]
Just for completeness and for documentation purposes:
I'm traveling today and I tried this in several public public networks (trains, airports). All of them blocked this or aborted this, with similar error messages then above.

Now that I'm back in my default network everything works as it should. So this confirms @merks' comment.

**Comment by merks** [comment]
I believe some locations block certain ports and that makes things not work.

**Comment by lak-proddev** [comment]
My mobile network works for me, instead of a broadband connection.
