### ISSUE TITLE
Palette cursors are double size on Linux Wayland hi-dpi

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#463]
Can someone please confirm the following?

Step to reproduce:

1. You need a display set to 200% hi-dpi (if not you can simulate this by setting the Environment variable `GDK_SCALE=2`)
2. Ubuntu 24.04 Wayland or other Wayland disto
3. Run a GEF based app with a palette and check the size of the cursors - they will be double size

This relates to this commit - https://github.com/eclipse/gef-classic/commit/4ee6cca0c26592e6a65dfa198211a400dcac8114

It seems that at some point in the past cursors under Wayland were the correct size but not now. I tested with Archi and the DBeaver app.

**Comment by ptziegler** [comment]
With GDK_SCALE=2 and the "normal" cursor for comparison

![image](https://github.com/user-attachments/assets/fb56d242-df6c-48bf-b635-e1889322e71c)

**Comment by ptziegler** [comment]
But I see the same thing on X11...
