### ISSUE TITLE
Convert gif images to png format

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#465]
GEF uses several gif images - 

https://github.com/eclipse/gef-classic/tree/master/org.eclipse.gef/icons
https://github.com/eclipse/gef-classic/tree/master/org.eclipse.gef/src/org/eclipse/gef/internal/icons

Some distributions of Linux might not have support to load gif files. See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1307

Perhaps these could be converted to png format in both standard and @2x sizes? (I don't have the artistic skill to do this)

**Comment by azoitl** [comment]
I can give it a try. Especially some of the internal icons would also be available in the platform. Maybe we can take some of theirs and reduce ours.

**Comment by ptziegler** [comment]
It's still wild to me that projects plan on dropping something as widespread as gifs...

Just as a note: From my experience, pngs tend to be much larger than gifs, unless you crank the compression level to the limit. 

I also remember it being possible to request funding from the EF. Perhaps it makes sense to commission a new set of icons instead? Especially since some icons (prominently the cursors) did not age gracefully.
Though I wouldn't even know where to start there...

**Comment by azoitl** [comment]
The biggest problem I see with gifs is that AFAIK there is no alpha channel. PNG icons blend here much nicer in and this is a plus for dark mode.

**Comment by merks** [comment]
Yes, there is one "color" that can be 100% transparent, but definitely no alpha.

**Comment by azoitl** [comment]
In the last two days I started working on migrating the align icons to pngs and also added 2x versions. Not fully done yet but you can see where it is going here: https://github.com/eclipse/gef-classic/commit/5cf918ec254c839c9beb5dffac34a9a2063feb19

I think for most icons I will be able to produce nice versions for the 2024-09 release.

One thing I noticed where pngs are also better is that you can get nicer gradients as png allow full 8 bit rgba colors. This is especially helpful for making icons fitting to the Eclipse UI guidelines.

**Comment by Phillipus** [comment]
@azoitl Thanks! They look good. :-)

**Comment by ptziegler** [comment]
A quick search resulted in the following list of GIFs that still need to be converted. @azoitl What, if any, icons are you currently working on? Most of the icons belong to the GEF bundle and I'd like to avoid both of us working on the same files.

- org.eclipse.gef
	- org/eclipse/gef/internal/icons/
		- [ ] add.gif
		- [ ] add-disabled.gif
		- [ ] arrow16.gif
		- [ ] arrow24.gif
		- [ ] category.ghif
		- [ ] customizer_dialog_title.gif
		- [ ] folder_closed.gif
		- [ ] marquee_nodes16.gif
		- [ ] marquee_nodes24.gif
		- [ ] marquee_wires16.gif
		- [ ] marquee_wires24.gif
		- [ ] marquee16.gif
		- [ ] marquee24.gif
		- [ ] move_down_disabled.gif
		- [ ] move_up_disabled.gif
		- [ ] palette_layout.gif
		- [ ] palette_left.gif
		- [ ] palette_right.gif
		- [ ] palette_view.gif
		- [ ] pin_view.gif
		- [ ] pinned.gif
		- [ ] prev_nav.gif
		- [ ] separator.gif
		- [ ] style_bold.gif
		- [ ] style_italic.gif
		- [ ] style_paragraph_center.gif
		- [ ] style_paragraph_left.gif
		- [ ] style_paragraph_right.gif
		- [ ] style_paragraph_rtl.gif
		- [ ] style_underline.gif
		- [ ] unpinned.gif
		- [ ] zoom_in.gif
		- [ ] zoom_out.gif
	- org/eclipse/gef/ui/stackview/icons
		- [ ] NORED.gif
		- [ ] REDOGRN.gif
		- [ ] stackDebug.gif
		- [ ] UNDOGRN.gif
		- [ ] YESGRN.gif
	- org/eclipse/gef/ui/console/icons
		- [ ] debugClear.gif
		- [ ] debugDND.gif
		- [ ] debugEditParts.gif
		- [ ] debugEvents.gif
		- [ ] debugFeedback.gif
		- [ ] debugGEF.gif
		- [ ] debugGlobal.gif
		- [ ] debugPaint.gif
		- [ ] debugStates.GIF
		- [ ] debugTools.gif
	- icons
		- [ ] palette_view.gif
- org.eclipse.zest.core
	- icons
		- [ ] back_arrow.gif

**Comment by azoitl** [comment]
I just experimented with the paragraph style icons. I would like to try looking into the marque select icons. But there I'm not yet sure which gradient to use.

**Comment by ptziegler** [comment]
> But there I'm not yet sure which gradient to use.

To get the colors right, I usually have the original GIF open in GIMP and then take the colors via the Color Picker. So for the marquee icons, the outer rectangle in e.g. `marquee16.gif`, the gradient start with #09569f at the bottom and end with #8f7728 at the top.

**Comment by azoitl** [comment]
> > But there I'm not yet sure which gradient to use.
> 
> To get the colors right, I usually have the original GIF open in GIMP and then take the colors via the Color Picker. So for the marquee icons, the outer rectangle in e.g. `marquee16.gif`, the gradient start with #09569f at the bottom and end with #8f7728 at the top.

My point was more about what colors to use. I have the feeling that in respect to the (Eclipse UI guidelines)[https://eclipse-platform.github.io/ui-best-practices/#design] the current colors seems a bit of.

**Comment by azoitl** [comment]
By now I have svgs of the marquee icons. I must admit working with inkscape has its advantages. Really like it.
No I only have to correctly generated the 4 pngs I need for the tools. but we are getting there.

**Comment by azoitl** [comment]
The code which uses the images from `org.eclipse.gef.ui.console.icons` is deprecated. I don't think it is worth the effort to redo this icons. 
Should we mark that API for removal in the second next release?

**Comment by ptziegler** [comment]
I noticed that as well and agree. It's not really worth the effort refactoring them when they should be used in the first place. I'm not even sure if both still work, in the first place...
