### ISSUE TITLE
Marquee Selection Tool causes unresponsive UI

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#466]
Our app has a Palette with the various Marquee Selection Tools. By default, these tools have their `setUnloadWhenFinished` set to true (i.e they remain selected in the palette). But there is a bug when one of these is selected:

1. Select a Marquee Selection tool from the palette
2. The mouse cursor will change to a plus sign
3. Hover the mouse over an area of the app that is not the diagram so the mouse cursor changes to the default cursor
4. Try clicking in the diagram - the UI is unresponsive

Seems that if the cursor is not the plus sign when the tool is selected all mouse clicks are ignored.

**Comment by Phillipus** [comment]
Here's what happens once the cursor has exited the diagram and clicked back on the diagram:

`AbstractTool` receives the mouse down event in `mouseDown(MouseEvent me, EditPartViewer viewer)`

This calls `isViewerImportant(EditPartViewer viewer)` in `MarqueeSelectionTool` and this calls `isCurrentViewerGraphical()`:

```java
    private boolean isCurrentViewerGraphical() {
        return getCurrentViewer() instanceof GraphicalViewer;
    }
```

But at this point the current viewer is null so the mouse down event is not propagated.

Somewhere, moving the cursor out of the diagram sets the current viewer to null.

**Comment by Phillipus** [comment]
Adding `System.out.println(viewer);` to `AbstractTool#setViewer(EditPartViewer viewer)` and moving the mouse I can see that the viewer is being set to null when the mouse exits the viewer but not being set back again to the viewer when the mouse enters again.

**Comment by ptziegler** [comment]
> Somewhere, moving the cursor out of the diagram sets the current viewer to null.

I assume you mean this?

https://github.com/eclipse/gef-classic/blob/e1d163b08c72039ce96efd2692edbda1ff06d6f9/org.eclipse.gef/src/org/eclipse/gef/tools/AbstractTool.java#L1616-L1626

**Comment by Phillipus** [comment]
> I assume you mean this?

That's behaving correctly, it should be set to null when exiting. But when `viewerEntered` is then called it calls `isViewerImportant(viewer)` which returns false.

**Comment by Phillipus** [comment]
It seems that `MarqueeSelectionTool` is the only tool that implements `isViewerImportant`.

Once the current viewer has been set to null in `AbstractTool#viewerExited` when the next `AbstractTool#viewerEntered` is called it calls  `MarqueeSelectionTool#`isViewerImportant` which by now will return false because the viewer is null.

**Comment by ptziegler** [comment]
> That's behaving correctly, it should be set to null when exiting. But when viewerEntered is then called it calls isViewerImportant(viewer) which returns false.

Yes. Because `isViewerImportant()` is called before `setViewer()`. So the viewer is still null at that point. This behavior seems to have been introduced with d94c624c8cd5b92b0568ac416bc400d68fe0ed7a. But it no immediately obvious whether that was intentional.

https://github.com/eclipse/gef-classic/blob/e1d163b08c72039ce96efd2692edbda1ff06d6f9/org.eclipse.gef/src/org/eclipse/gef/tools/AbstractTool.java#L1596-L1606

**Comment by ptziegler** [comment]
I believe that change was a misguided optimization. So I think the solution is to partially revert that commit.

**Comment by Phillipus** [comment]
The comment in `MarqueeSelectionTool#isViewerImportant` is:

> MarqueeSelectionTool is only interested in GraphicalViewers, not TreeViewers.

so maybe that should be checked instead?

**Comment by ptziegler** [comment]
> so maybe that should be checked instead?

That's how it used to be. With https://github.com/eclipse/gef-classic/commit/d94c624c8cd5b92b0568ac416bc400d68fe0ed7a, the method was changed from

```java
protected boolean isViewerImportant(EditPartViewer viewer) {
	return viewer instanceof GraphicalViewer;
}
```

to

```java
protected boolean isViewerImportant(EditPartViewer viewer) {
	return isCurrentViewerGraphical();
}
```

for no obvious reason. Latter is what's still used today and what is causing the problem.

**Comment by Phillipus** [comment]
But it's effectively the same:

```java
    private boolean isCurrentViewerGraphical() {
        return getCurrentViewer() instanceof GraphicalViewer;
    }
```

isCurrentViewerGraphical is also used in `handleButtonDown`

**Comment by Phillipus** [comment]
I think the problem is the logic in `AbstractTool#viewerEntered` calling `isViewerImportant` which of course might return false if the viewer is null because `AbstractTool#viewerExited` set it to null in the first place!

**Comment by ptziegler** [comment]
That's what I meant. The underlying logic is the same, just applied on different objects. For `isViewerImportant()`, the argument should be used and for e.g. handleButtonDown(), the current viewer.

**Comment by Phillipus** [comment]
> That's what I meant. The underlying logic is the same, just applied on different objects. For isViewerImportant(), the argument should be used and for e.g. handleButtonDown(), the current viewer.

My bad. `viewer` is the argument, yes you're right. I changed it to your suggestion and it works now.

**Comment by ptziegler** [comment]
The same issue also happens when the marquee selection tool is activated, without moving the cursor into the editor. https://github.com/eclipse/gef-classic/pull/467 creates a small test case that illustrates the behavior.

**Comment by Phillipus** [comment]
> The same issue also happens when the marquee selection tool is activated

I can only activate the marquee selection tool when clicking on an editor.


BTW - thanks for looking at this, your analysis is way better than mine! :-)
