### ISSUE TITLE
Dependabot checks for GitHub actions don't work

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#471]
Looking at the versions used by our workflows, I noticed that several plugins are grossly oudated. Leading me to the conclusion that the dependabot update either doesn't work or is not detecting the newer versions.

Example:

actions/checkout@v4 -> https://github.com/actions/checkout/releases/tag/v4.1.7
actions/upload-artifact@v4 -> https://github.com/actions/upload-artifact/releases/tag/v4.3.4
coactions/setup-xvfb@v1 -> https://github.com/coactions/setup-xvfb/releases/tag/v1.0.1

**Comment by ptziegler** [comment]
I see what the issue is: We only check for changes in the major version. So new minor or micro releases are ignored. Should we change that?

![image](https://github.com/eclipse/gef-classic/assets/70652978/4d8d5518-ed36-4b7f-9a3f-d1f050804717)

**Comment by azoitl** [comment]
Definitely we should do that. I'm a bit confused why that happens because I based this on the dependabot checker used in the ui guidelines.
