### ISSUE TITLE
Figure::findMouseEventTargetInDescendantsAt() seems not reentrant

### ISSUE THREAD

**Issue by ddscharfe** [eclipse/gef-classic#495]
This is similar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=81725 (fixed by 4a091db1f84922e59ee0f7d36586c8657e8c9e86), but for finding mouse event targets. There was already a ticket for this (https://bugs.eclipse.org/bugs/show_bug.cgi?id=226103) which for some reason was resolved as `WORKSFORME` later.

When a figure has multiple children where one child uses local coordinates, this can lead to wrong event target detection, see comments 1 and 2:

```Java
	protected IFigure findMouseEventTargetInDescendantsAt(int x, int y) {
		PRIVATE_POINT.setLocation(x, y);
		translateFromParent(PRIVATE_POINT);

		if (!getClientArea(Rectangle.SINGLETON).contains(PRIVATE_POINT)) {
			return null;
		}

		for (IFigure fig : getChildrenRevIterable()) {
			if (fig.isVisible() && fig.isEnabled() && fig.containsPoint(PRIVATE_POINT.x, PRIVATE_POINT.y)) {
                                // (1) This call will change PRIVATE_POINT if fig uses local coordinates
				fig = fig.findMouseEventTargetAt(PRIVATE_POINT.x, PRIVATE_POINT.y);
				if (fig != null) {
					return fig;
				}
                                // (2) subsequent iterations will use the translated coordinates
			}
		}
		return null;
	}
```

**Comment by ptziegler** [comment]
>  There was already a ticket for this (https://bugs.eclipse.org/bugs/show_bug.cgi?id=226103) which for some reason was resolved as WORKSFORME later.

My assumption is that this is a misunderstanding regarding the example provided by Manuel. I can see the same issue with the latest version (clicking the button should NOT highlight the yellow rectangle), so the wrong behavior definitely still exists.

Storing the position in local coordinates (similar to bug [81725](https://bugs.eclipse.org/bugs/show_bug.cgi?id=81725))  solves the issue, but I'm still working on integrating the snippet in our test suite to avoid any regressions.
