### ISSUE TITLE
Rename gef-legacy to gef-classic

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#5]
gef-legacy gives a very negative feeling about the project. I suggest we rename it to gef-swt.

**Comment by azoitl** [comment]
As in GEF5 gef fx is just one feature of the whole GEF 5 suite I find gef-swt to limiting in scope. How about gef-classic?

**Comment by vogella** [comment]
@azoitl sounds also fine for me

Any other opinions?

**Comment by serge-rider** [comment]
`gef-classic` sounds good 👍

**Comment by vogella** [comment]
@mwienand can you approved as project lead?

**Comment by mwienand** [comment]
Sounds good to me. Btw, GEF Classic reminds me of OPC Classic.

**Comment by vogella** [comment]
Thanks @mwienand 

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1105

**Comment by vogella** [comment]
Done, thanks.

@mwienand do you if we have an active build job for the old legacy repo which we need to update?

**Comment by azoitl** [comment]
> Sounds good to me. Btw, GEF Classic reminds me of OPC Classic.

Maybe that's where I got the inspiration from ;-)
