### ISSUE TITLE
GEF, icon is missing: icon "palette_view.gif" (org.eclipse.gef/icons/palette_view.gif)

### ISSUE THREAD

**Issue by speckyspooky** [eclipse/gef-classic#512]
Currently we work on the next release of BIRT 4.17.
There we use the latest eclipse plattform version:
Version: 2024-09 (4.33)
Build id: I20240815-1810

The eclipse-designer with active BIRT-view has one register with the icon of a color palette normally.
But currently the icon is not longer listed and the eclipse warning means that the icon is missing from "org.eclipse.gef/icons/palette_view.gif)" - see screen below.

Instead of the palette icon we get a red rectangle or a small fram-icon (as default icon).

Is the cion complettly removed or is the icon changed?
What can we do to fix it?

I tried a small research here on GEF but I figured out no good hint of a change for that icon.

![grafik](https://github.com/user-attachments/assets/a7540908-3394-4090-833c-19f40712cacf)

**Comment by ptziegler** [comment]
The palette view is contributed here, where the new png icon is used:

https://github.com/eclipse/gef-classic/blob/e5d6bac76ff38625b7c04877c0582452f04055ff/org.eclipse.gef/plugin.xml#L211-L220

A quick search doesn't show any indication that the old gif icon is still referenced, so I don't believe there is any misconfiguration on GEF side.

![image](https://github.com/user-attachments/assets/222a806a-b2ca-412d-b213-d4ae6c10e692)

After trying the latest GEF plugin, I can see that the icon is correctly shown in the Palette view:

![image](https://github.com/user-attachments/assets/ff901097-9940-4291-82a8-f685c5bde44a)

Weirdly enough, I get the same error when opening the old BIRT workspace I have checked out...

![image](https://github.com/user-attachments/assets/1cf3af0e-335b-4798-b351-cb0a5be3e3b1)

A quick search reveals that the old icon is still referenced in the workspace.xmi file located in the metadata folder. So I agree with @merks theory that the Eclipse itself is caching those URLs which are then not updated properly.

![image](https://github.com/user-attachments/assets/08b5b3fd-4b0d-4055-aa38-62f5b538c66b)

**Comment by ptziegler** [comment]
After starting the application with `-DclearPersistedState`, I now get the following error:

```
!MESSAGE Unable to create resource URLImageDescriptor(platform:/plugin/org.eclipse.gef/src/org/eclipse/gef/internal/icons/palette_view.png)
!STACK 0
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource URLImageDescriptor(platform:/plugin/org.eclipse.gef/src/org/eclipse/gef/internal/icons/palette_view.png)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:231)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:95)
	at org.eclipse.jface.resource.LocalResourceManager.allocate(LocalResourceManager.java:71)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	...
```

Meaning the new URI is used, but the path can't be resolved.

**Comment by ptziegler** [comment]
> platform:/plugin/org.eclipse.gef/src/org/eclipse/gef/internal/icons/palette_view.png

This path only makes sense when GEF is checked out locally. In the jar, the "src" segment doesn't exist. I've created #513 to address this oversight but outside of that, I'm not sure if there is anything else that can be done from our side.

**Comment by ptziegler** [comment]
After the fix has been applied:

![image](https://github.com/user-attachments/assets/f12545e2-bd25-4377-aba9-60df3add9049)

**Comment by ptziegler** [comment]
Is there anything more that can be done from our side? The path to the "Palette View" icon has been fixed, but one needs to explicitly clear the _workbench.xmi_ in order to get the old value out of the IDE. But that's not something we really have control over...

But that only affects old workspaces. With a fresh one, the new icons should automatically be used.

**Comment by speckyspooky** [comment]
Many thanks for the support.
The rest will be steps on our side.
