### ISSUE TITLE
Tooltips on GEF palette are broken on Linux/Wayland 

### ISSUE THREAD

**Issue by rhornig** [eclipse/gef-classic#568]
GEF version 3.21

The tooltips on the palette are shown as a top-level window with decoration in the center of the desktop. Note that this happens ONLY on Linux in a **Wayland** session and only for the palette items. 

![image](https://github.com/user-attachments/assets/6c91015d-99d8-4c2d-8655-2d88b7077be8)

**Comment by merks** [comment]
It would seem inconceivable that a Window manager should decide that there should be no way to set the location of a shell, but that appears to be the case and is likely the cause of the problem:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/790

**Comment by rhornig** [comment]
It seems to be a regression in 3.21 because I don't seem to remember this issue with 3.20. Perhaps caused by a side effect of this commit? https://github.com/eclipse/gef-classic/commit/1836f13a4f47a5ea4d4453ac3d44d8a79c537df6

**Comment by ptziegler** [comment]
Likely a duplicate of https://github.com/eclipse/gef-classic/issues/555. Does this also happen with the current nightly build?

**Comment by ptziegler** [comment]
> The real issue is that on Linux Wayland the tooltip is displayed in the centre of the screen, not over the object, and grabs the focus. This is because the Shell created in PopupHelper has the Display as its parent because of the change in https://github.com/eclipse/gef-classic/commit/843e56c0df42aec34a487b97483a0b6c866fff95

**Comment by rhornig** [comment]
> Likely a duplicate of #555. Does this also happen with the current nightly build?

Indeed this is a duplicate and does not happen on the head version anymore.
