### ISSUE TITLE
Update https://www.eclipse.org/gef/downloads/

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#60]
We should find where https://www.eclipse.org/gef/downloads/ is maintained and update it with the new information about GEF classic.

**Comment by vogella** [comment]
@[azoitl](https://github.com/eclipse/gef-classic/issues?q=is%3Aissue+is%3Aopen+author%3Aazoitl) can you take this one?

**Comment by vogella** [comment]
I will update https://projects.eclipse.org/projects/tools.gef/downloads

**Comment by azoitl** [comment]
> @[azoitl](https://github.com/eclipse/gef-classic/issues?q=is%3Aissue+is%3Aopen+author%3Aazoitl) can you take this one?

@vogella yes will do

**Comment by vogella** [comment]
I updated https://projects.eclipse.org/projects/tools.gef

**Comment by azoitl** [comment]
I did a first update of https://www.eclipse.org/gef/downloads/ by replacing all GEF legacy to GEF classic: https://git.eclipse.org/r/c/www.eclipse.org/gef/+/193143

The list is automatically generated by scripts searching through directory on download.eclipse.org. Are we planning to publish zip files of download sites there es well? Should we make the link to the current update sites, namely  https://projects.eclipse.org/projects/tools.gef more promient?

**Comment by azoitl** [comment]
> I updated https://projects.eclipse.org/projects/tools.gef

Is it possible to get the update sites as clickable links?

**Comment by vogella** [comment]
> > I updated https://projects.eclipse.org/projects/tools.gef
> 
> Is it possible to get the update sites as clickable links?

I don't think so.

**Comment by vogella** [comment]
> The list is automatically generated by scripts searching through directory on download.eclipse.org. Are we planning to publish zip files of download sites there es well? Should we make the link to the current update sites, namely https://projects.eclipse.org/projects/tools.gef more promient?

I think zip files are not really helpful, are they? I would suggest to better invest in publish to Maven central.

**Comment by azoitl** [comment]
Only if you work in an isolated setting. I'm also not to sure about Maven central. Because GEF is only suitable within the Eclipse Platform. Therefore anything p2 and target platform usable is the thing that makes most sense, and will keep the life of adopters easy.

**Comment by vogella** [comment]
Ok, lets close
