### ISSUE TITLE
Pushlish to Maven central

### ISSUE THREAD

**Issue by vogella** [eclipse/gef-classic#67]
Would be great if we can publish each release to Maven central so that GEF classic is easier to consume for regular Maven / Gradle users.

We could use GEF also as test ground for automating publishing to Maven via Eclipse process, for example @laeubi would also like to publish more frequently p2 and if we can automate this here, we could apply this learning also to platform.

@HannesWell or @laeubi does Tycho provide support for publishing to Maven or is this just standard Maven stuff? Do you publish Tycho or M2e to Maven central so that we can see your configuration?

**Comment by laeubi** [comment]
See https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#enhanced-support-for-maven-ci-friendly-versions what might make this much more convenient than the usual flows.

**Comment by laeubi** [comment]
One could also publish to eclipse-maven repo or github packages if the sonatype seems not fit.

Beside that `maven-release-plugin` are reported to not work well with tycho, so CI friendly versions and mvn deploy might be easier to archive.

**Comment by vogella** [comment]
Lets reconsider this once platform have streamlined the process so that we can "steal" it.
