### ISSUE TITLE
Update site for release 3.13.0 does not include the sources

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gef-classic#68]
The new GEF Classic repo do not include the sources.

Compare:
* https://download.eclipse.org/tools/gef/classic/releases/3.13.0
* https://download.eclipse.org/tools/gef/updates/legacy/releases/4.0.0_gef-master_1952

That's quite annoying when working on downstream projects.

**Comment by vogella** [comment]
Thanks for the report, will fix this. Sorry for not replying to this comment in the other issue, I was / am busy but should have time to fix this early next week.

Unless someone else is faster with a PR....

**Comment by azoitl** [comment]
I'm on it. Was also busy. But now trying to find out what is missing.

**Comment by vogella** [comment]
@azoitl 
IIRC the source features need to be added to the cateogory manually, as they are not available via the Tycho build so PDE does not know them. You could / should theri ID if you point with the p2 installation dialog to your local update site.

**Comment by azoitl** [comment]
@vogella thx for the hint. After some googleing I found that information. I have a pull request that at least when I run the tycho build locally the p2 repo has the right source packages.

**Comment by vogella** [comment]
Thanks @azoitl 

@pcdavid i updated the release update site. Can you check if you can see and use the source features?

**Comment by pcdavid** [comment]
Can confirm it's now available :+1:
Thanks for the quick response.
