### ISSUE TITLE
Remove com.ibm.icu package dependencies

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#92]
The `org.eclipse.draw2d`, `org.eclipse.gef` and `org.eclipse.zest.core` manifests import package `com.ibm.icu.text`. The following classes are used in the code:

```
com.ibm.icu.text.Bidi
com.ibm.icu.text.BreakIterator
com.ibm.icu.text.DecimalFormat
com.ibm.icu.text.NumberFormat
com.ibm.icu.text.MessageFormat
```

By removing the import package a straight substitution of the following classes can be used instead:

```
java.text.Bidi
java.text.BreakIterator
java.text.DecimalFormat
java.text.NumberFormat
java.text.MessageFormat
```

The code compiles but I have no idea if the `java.text.*` versions of these classes have exactly the same implementations as the `com.ibm.icu.*` versions. Does anyone know if there are differences?

**Comment by vogella** [comment]
Please provide PR so that we can try it out

**Comment by Phillipus** [comment]
> Please provide PR so that we can try it out

https://github.com/eclipse/gef-classic/pull/93

**Comment by Phillipus** [comment]
Close this one now that the PR has been merged.

**Comment by Phillipus** [comment]
This has caused changed behaviour in line breaks. See #116
